// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/message.proto

package com.duke.proto.data;

/**
 * Protobuf enum {@code com.duke.proto.data.CHARACTER_STATE}
 */
public enum CHARACTER_STATE
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>IDLE = 0;</code>
   */
  IDLE(0),
  /**
   * <code>MOVE = 1;</code>
   */
  MOVE(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>IDLE = 0;</code>
   */
  public static final int IDLE_VALUE = 0;
  /**
   * <code>MOVE = 1;</code>
   */
  public static final int MOVE_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static CHARACTER_STATE valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static CHARACTER_STATE forNumber(int value) {
    switch (value) {
      case 0: return IDLE;
      case 1: return MOVE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<CHARACTER_STATE>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      CHARACTER_STATE> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<CHARACTER_STATE>() {
          public CHARACTER_STATE findValueByNumber(int number) {
            return CHARACTER_STATE.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.duke.proto.data.Message.getDescriptor().getEnumTypes().get(3);
  }

  private static final CHARACTER_STATE[] VALUES = values();

  public static CHARACTER_STATE valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private CHARACTER_STATE(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:com.duke.proto.data.CHARACTER_STATE)
}

