// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/message.proto

package com.duke.proto.data;

public interface MapTeleportRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.duke.proto.data.MapTeleportRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 teleporterId = 1;</code>
   * @return The teleporterId.
   */
  int getTeleporterId();
}
