// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/message.proto

package com.duke.proto.data;

/**
 * Protobuf type {@code com.duke.proto.data.NEntity}
 */
public final class NEntity extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.duke.proto.data.NEntity)
    NEntityOrBuilder {
private static final long serialVersionUID = 0L;
  // Use NEntity.newBuilder() to construct.
  private NEntity(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private NEntity() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new NEntity();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private NEntity(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt32();
            break;
          }
          case 18: {
            com.duke.proto.data.NVector3.Builder subBuilder = null;
            if (position_ != null) {
              subBuilder = position_.toBuilder();
            }
            position_ = input.readMessage(com.duke.proto.data.NVector3.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(position_);
              position_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            com.duke.proto.data.NVector3.Builder subBuilder = null;
            if (direction_ != null) {
              subBuilder = direction_.toBuilder();
            }
            direction_ = input.readMessage(com.duke.proto.data.NVector3.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(direction_);
              direction_ = subBuilder.buildPartial();
            }

            break;
          }
          case 32: {

            speed_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.duke.proto.data.Message.internal_static_com_duke_proto_data_NEntity_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.duke.proto.data.Message.internal_static_com_duke_proto_data_NEntity_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.duke.proto.data.NEntity.class, com.duke.proto.data.NEntity.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public int getId() {
    return id_;
  }

  public static final int POSITION_FIELD_NUMBER = 2;
  private com.duke.proto.data.NVector3 position_;
  /**
   * <code>.com.duke.proto.data.NVector3 position = 2;</code>
   * @return Whether the position field is set.
   */
  @java.lang.Override
  public boolean hasPosition() {
    return position_ != null;
  }
  /**
   * <code>.com.duke.proto.data.NVector3 position = 2;</code>
   * @return The position.
   */
  @java.lang.Override
  public com.duke.proto.data.NVector3 getPosition() {
    return position_ == null ? com.duke.proto.data.NVector3.getDefaultInstance() : position_;
  }
  /**
   * <code>.com.duke.proto.data.NVector3 position = 2;</code>
   */
  @java.lang.Override
  public com.duke.proto.data.NVector3OrBuilder getPositionOrBuilder() {
    return getPosition();
  }

  public static final int DIRECTION_FIELD_NUMBER = 3;
  private com.duke.proto.data.NVector3 direction_;
  /**
   * <code>.com.duke.proto.data.NVector3 direction = 3;</code>
   * @return Whether the direction field is set.
   */
  @java.lang.Override
  public boolean hasDirection() {
    return direction_ != null;
  }
  /**
   * <code>.com.duke.proto.data.NVector3 direction = 3;</code>
   * @return The direction.
   */
  @java.lang.Override
  public com.duke.proto.data.NVector3 getDirection() {
    return direction_ == null ? com.duke.proto.data.NVector3.getDefaultInstance() : direction_;
  }
  /**
   * <code>.com.duke.proto.data.NVector3 direction = 3;</code>
   */
  @java.lang.Override
  public com.duke.proto.data.NVector3OrBuilder getDirectionOrBuilder() {
    return getDirection();
  }

  public static final int SPEED_FIELD_NUMBER = 4;
  private int speed_;
  /**
   * <code>int32 speed = 4;</code>
   * @return The speed.
   */
  @java.lang.Override
  public int getSpeed() {
    return speed_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeInt32(1, id_);
    }
    if (position_ != null) {
      output.writeMessage(2, getPosition());
    }
    if (direction_ != null) {
      output.writeMessage(3, getDirection());
    }
    if (speed_ != 0) {
      output.writeInt32(4, speed_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (position_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getPosition());
    }
    if (direction_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getDirection());
    }
    if (speed_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, speed_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.duke.proto.data.NEntity)) {
      return super.equals(obj);
    }
    com.duke.proto.data.NEntity other = (com.duke.proto.data.NEntity) obj;

    if (getId()
        != other.getId()) return false;
    if (hasPosition() != other.hasPosition()) return false;
    if (hasPosition()) {
      if (!getPosition()
          .equals(other.getPosition())) return false;
    }
    if (hasDirection() != other.hasDirection()) return false;
    if (hasDirection()) {
      if (!getDirection()
          .equals(other.getDirection())) return false;
    }
    if (getSpeed()
        != other.getSpeed()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    if (hasPosition()) {
      hash = (37 * hash) + POSITION_FIELD_NUMBER;
      hash = (53 * hash) + getPosition().hashCode();
    }
    if (hasDirection()) {
      hash = (37 * hash) + DIRECTION_FIELD_NUMBER;
      hash = (53 * hash) + getDirection().hashCode();
    }
    hash = (37 * hash) + SPEED_FIELD_NUMBER;
    hash = (53 * hash) + getSpeed();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.duke.proto.data.NEntity parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.duke.proto.data.NEntity parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.duke.proto.data.NEntity parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.duke.proto.data.NEntity parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.duke.proto.data.NEntity parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.duke.proto.data.NEntity parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.duke.proto.data.NEntity parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.duke.proto.data.NEntity parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.duke.proto.data.NEntity parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.duke.proto.data.NEntity parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.duke.proto.data.NEntity parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.duke.proto.data.NEntity parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.duke.proto.data.NEntity prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.duke.proto.data.NEntity}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.duke.proto.data.NEntity)
      com.duke.proto.data.NEntityOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.duke.proto.data.Message.internal_static_com_duke_proto_data_NEntity_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.duke.proto.data.Message.internal_static_com_duke_proto_data_NEntity_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.duke.proto.data.NEntity.class, com.duke.proto.data.NEntity.Builder.class);
    }

    // Construct using com.duke.proto.data.NEntity.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0;

      if (positionBuilder_ == null) {
        position_ = null;
      } else {
        position_ = null;
        positionBuilder_ = null;
      }
      if (directionBuilder_ == null) {
        direction_ = null;
      } else {
        direction_ = null;
        directionBuilder_ = null;
      }
      speed_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.duke.proto.data.Message.internal_static_com_duke_proto_data_NEntity_descriptor;
    }

    @java.lang.Override
    public com.duke.proto.data.NEntity getDefaultInstanceForType() {
      return com.duke.proto.data.NEntity.getDefaultInstance();
    }

    @java.lang.Override
    public com.duke.proto.data.NEntity build() {
      com.duke.proto.data.NEntity result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.duke.proto.data.NEntity buildPartial() {
      com.duke.proto.data.NEntity result = new com.duke.proto.data.NEntity(this);
      result.id_ = id_;
      if (positionBuilder_ == null) {
        result.position_ = position_;
      } else {
        result.position_ = positionBuilder_.build();
      }
      if (directionBuilder_ == null) {
        result.direction_ = direction_;
      } else {
        result.direction_ = directionBuilder_.build();
      }
      result.speed_ = speed_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.duke.proto.data.NEntity) {
        return mergeFrom((com.duke.proto.data.NEntity)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.duke.proto.data.NEntity other) {
      if (other == com.duke.proto.data.NEntity.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (other.hasPosition()) {
        mergePosition(other.getPosition());
      }
      if (other.hasDirection()) {
        mergeDirection(other.getDirection());
      }
      if (other.getSpeed() != 0) {
        setSpeed(other.getSpeed());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.duke.proto.data.NEntity parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.duke.proto.data.NEntity) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int id_ ;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0;
      onChanged();
      return this;
    }

    private com.duke.proto.data.NVector3 position_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.duke.proto.data.NVector3, com.duke.proto.data.NVector3.Builder, com.duke.proto.data.NVector3OrBuilder> positionBuilder_;
    /**
     * <code>.com.duke.proto.data.NVector3 position = 2;</code>
     * @return Whether the position field is set.
     */
    public boolean hasPosition() {
      return positionBuilder_ != null || position_ != null;
    }
    /**
     * <code>.com.duke.proto.data.NVector3 position = 2;</code>
     * @return The position.
     */
    public com.duke.proto.data.NVector3 getPosition() {
      if (positionBuilder_ == null) {
        return position_ == null ? com.duke.proto.data.NVector3.getDefaultInstance() : position_;
      } else {
        return positionBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.duke.proto.data.NVector3 position = 2;</code>
     */
    public Builder setPosition(com.duke.proto.data.NVector3 value) {
      if (positionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        position_ = value;
        onChanged();
      } else {
        positionBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.duke.proto.data.NVector3 position = 2;</code>
     */
    public Builder setPosition(
        com.duke.proto.data.NVector3.Builder builderForValue) {
      if (positionBuilder_ == null) {
        position_ = builderForValue.build();
        onChanged();
      } else {
        positionBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.duke.proto.data.NVector3 position = 2;</code>
     */
    public Builder mergePosition(com.duke.proto.data.NVector3 value) {
      if (positionBuilder_ == null) {
        if (position_ != null) {
          position_ =
            com.duke.proto.data.NVector3.newBuilder(position_).mergeFrom(value).buildPartial();
        } else {
          position_ = value;
        }
        onChanged();
      } else {
        positionBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.duke.proto.data.NVector3 position = 2;</code>
     */
    public Builder clearPosition() {
      if (positionBuilder_ == null) {
        position_ = null;
        onChanged();
      } else {
        position_ = null;
        positionBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.duke.proto.data.NVector3 position = 2;</code>
     */
    public com.duke.proto.data.NVector3.Builder getPositionBuilder() {
      
      onChanged();
      return getPositionFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.duke.proto.data.NVector3 position = 2;</code>
     */
    public com.duke.proto.data.NVector3OrBuilder getPositionOrBuilder() {
      if (positionBuilder_ != null) {
        return positionBuilder_.getMessageOrBuilder();
      } else {
        return position_ == null ?
            com.duke.proto.data.NVector3.getDefaultInstance() : position_;
      }
    }
    /**
     * <code>.com.duke.proto.data.NVector3 position = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.duke.proto.data.NVector3, com.duke.proto.data.NVector3.Builder, com.duke.proto.data.NVector3OrBuilder> 
        getPositionFieldBuilder() {
      if (positionBuilder_ == null) {
        positionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.duke.proto.data.NVector3, com.duke.proto.data.NVector3.Builder, com.duke.proto.data.NVector3OrBuilder>(
                getPosition(),
                getParentForChildren(),
                isClean());
        position_ = null;
      }
      return positionBuilder_;
    }

    private com.duke.proto.data.NVector3 direction_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.duke.proto.data.NVector3, com.duke.proto.data.NVector3.Builder, com.duke.proto.data.NVector3OrBuilder> directionBuilder_;
    /**
     * <code>.com.duke.proto.data.NVector3 direction = 3;</code>
     * @return Whether the direction field is set.
     */
    public boolean hasDirection() {
      return directionBuilder_ != null || direction_ != null;
    }
    /**
     * <code>.com.duke.proto.data.NVector3 direction = 3;</code>
     * @return The direction.
     */
    public com.duke.proto.data.NVector3 getDirection() {
      if (directionBuilder_ == null) {
        return direction_ == null ? com.duke.proto.data.NVector3.getDefaultInstance() : direction_;
      } else {
        return directionBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.duke.proto.data.NVector3 direction = 3;</code>
     */
    public Builder setDirection(com.duke.proto.data.NVector3 value) {
      if (directionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        direction_ = value;
        onChanged();
      } else {
        directionBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.duke.proto.data.NVector3 direction = 3;</code>
     */
    public Builder setDirection(
        com.duke.proto.data.NVector3.Builder builderForValue) {
      if (directionBuilder_ == null) {
        direction_ = builderForValue.build();
        onChanged();
      } else {
        directionBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.duke.proto.data.NVector3 direction = 3;</code>
     */
    public Builder mergeDirection(com.duke.proto.data.NVector3 value) {
      if (directionBuilder_ == null) {
        if (direction_ != null) {
          direction_ =
            com.duke.proto.data.NVector3.newBuilder(direction_).mergeFrom(value).buildPartial();
        } else {
          direction_ = value;
        }
        onChanged();
      } else {
        directionBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.duke.proto.data.NVector3 direction = 3;</code>
     */
    public Builder clearDirection() {
      if (directionBuilder_ == null) {
        direction_ = null;
        onChanged();
      } else {
        direction_ = null;
        directionBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.duke.proto.data.NVector3 direction = 3;</code>
     */
    public com.duke.proto.data.NVector3.Builder getDirectionBuilder() {
      
      onChanged();
      return getDirectionFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.duke.proto.data.NVector3 direction = 3;</code>
     */
    public com.duke.proto.data.NVector3OrBuilder getDirectionOrBuilder() {
      if (directionBuilder_ != null) {
        return directionBuilder_.getMessageOrBuilder();
      } else {
        return direction_ == null ?
            com.duke.proto.data.NVector3.getDefaultInstance() : direction_;
      }
    }
    /**
     * <code>.com.duke.proto.data.NVector3 direction = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.duke.proto.data.NVector3, com.duke.proto.data.NVector3.Builder, com.duke.proto.data.NVector3OrBuilder> 
        getDirectionFieldBuilder() {
      if (directionBuilder_ == null) {
        directionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.duke.proto.data.NVector3, com.duke.proto.data.NVector3.Builder, com.duke.proto.data.NVector3OrBuilder>(
                getDirection(),
                getParentForChildren(),
                isClean());
        direction_ = null;
      }
      return directionBuilder_;
    }

    private int speed_ ;
    /**
     * <code>int32 speed = 4;</code>
     * @return The speed.
     */
    @java.lang.Override
    public int getSpeed() {
      return speed_;
    }
    /**
     * <code>int32 speed = 4;</code>
     * @param value The speed to set.
     * @return This builder for chaining.
     */
    public Builder setSpeed(int value) {
      
      speed_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 speed = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearSpeed() {
      
      speed_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.duke.proto.data.NEntity)
  }

  // @@protoc_insertion_point(class_scope:com.duke.proto.data.NEntity)
  private static final com.duke.proto.data.NEntity DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.duke.proto.data.NEntity();
  }

  public static com.duke.proto.data.NEntity getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NEntity>
      PARSER = new com.google.protobuf.AbstractParser<NEntity>() {
    @java.lang.Override
    public NEntity parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new NEntity(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<NEntity> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<NEntity> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.duke.proto.data.NEntity getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

