// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/message.proto

package com.duke.proto.data;

public interface UserLoginResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.duke.proto.data.UserLoginResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.duke.proto.data.RESULT result = 1;</code>
   * @return The enum numeric value on the wire for result.
   */
  int getResultValue();
  /**
   * <code>.com.duke.proto.data.RESULT result = 1;</code>
   * @return The result.
   */
  com.duke.proto.data.RESULT getResult();

  /**
   * <code>string errormsg = 2;</code>
   * @return The errormsg.
   */
  java.lang.String getErrormsg();
  /**
   * <code>string errormsg = 2;</code>
   * @return The bytes for errormsg.
   */
  com.google.protobuf.ByteString
      getErrormsgBytes();

  /**
   * <code>.com.duke.proto.data.NUserInfo userinfo = 3;</code>
   * @return Whether the userinfo field is set.
   */
  boolean hasUserinfo();
  /**
   * <code>.com.duke.proto.data.NUserInfo userinfo = 3;</code>
   * @return The userinfo.
   */
  com.duke.proto.data.NUserInfo getUserinfo();
  /**
   * <code>.com.duke.proto.data.NUserInfo userinfo = 3;</code>
   */
  com.duke.proto.data.NUserInfoOrBuilder getUserinfoOrBuilder();
}
