// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.duke.protobuf.data;

/**
 * <pre>
 *&#47; 背包保存
 * </pre>
 *
 * Protobuf type {@code com.duke.protobuf.data.BagSaveRequest}
 */
public final class BagSaveRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.duke.protobuf.data.BagSaveRequest)
    BagSaveRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BagSaveRequest.newBuilder() to construct.
  private BagSaveRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BagSaveRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new BagSaveRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BagSaveRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.duke.protobuf.data.NBagInfo.Builder subBuilder = null;
            if (bagInfo_ != null) {
              subBuilder = bagInfo_.toBuilder();
            }
            bagInfo_ = input.readMessage(com.duke.protobuf.data.NBagInfo.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(bagInfo_);
              bagInfo_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.duke.protobuf.data.Message.internal_static_com_duke_protobuf_data_BagSaveRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.duke.protobuf.data.Message.internal_static_com_duke_protobuf_data_BagSaveRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.duke.protobuf.data.BagSaveRequest.class, com.duke.protobuf.data.BagSaveRequest.Builder.class);
  }

  public static final int BAGINFO_FIELD_NUMBER = 1;
  private com.duke.protobuf.data.NBagInfo bagInfo_;
  /**
   * <code>.com.duke.protobuf.data.NBagInfo bagInfo = 1;</code>
   * @return Whether the bagInfo field is set.
   */
  @java.lang.Override
  public boolean hasBagInfo() {
    return bagInfo_ != null;
  }
  /**
   * <code>.com.duke.protobuf.data.NBagInfo bagInfo = 1;</code>
   * @return The bagInfo.
   */
  @java.lang.Override
  public com.duke.protobuf.data.NBagInfo getBagInfo() {
    return bagInfo_ == null ? com.duke.protobuf.data.NBagInfo.getDefaultInstance() : bagInfo_;
  }
  /**
   * <code>.com.duke.protobuf.data.NBagInfo bagInfo = 1;</code>
   */
  @java.lang.Override
  public com.duke.protobuf.data.NBagInfoOrBuilder getBagInfoOrBuilder() {
    return getBagInfo();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (bagInfo_ != null) {
      output.writeMessage(1, getBagInfo());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (bagInfo_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getBagInfo());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.duke.protobuf.data.BagSaveRequest)) {
      return super.equals(obj);
    }
    com.duke.protobuf.data.BagSaveRequest other = (com.duke.protobuf.data.BagSaveRequest) obj;

    if (hasBagInfo() != other.hasBagInfo()) return false;
    if (hasBagInfo()) {
      if (!getBagInfo()
          .equals(other.getBagInfo())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasBagInfo()) {
      hash = (37 * hash) + BAGINFO_FIELD_NUMBER;
      hash = (53 * hash) + getBagInfo().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.duke.protobuf.data.BagSaveRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.duke.protobuf.data.BagSaveRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.duke.protobuf.data.BagSaveRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.duke.protobuf.data.BagSaveRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.duke.protobuf.data.BagSaveRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.duke.protobuf.data.BagSaveRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.duke.protobuf.data.BagSaveRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.duke.protobuf.data.BagSaveRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.duke.protobuf.data.BagSaveRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.duke.protobuf.data.BagSaveRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.duke.protobuf.data.BagSaveRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.duke.protobuf.data.BagSaveRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.duke.protobuf.data.BagSaveRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *&#47; 背包保存
   * </pre>
   *
   * Protobuf type {@code com.duke.protobuf.data.BagSaveRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.duke.protobuf.data.BagSaveRequest)
      com.duke.protobuf.data.BagSaveRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.duke.protobuf.data.Message.internal_static_com_duke_protobuf_data_BagSaveRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.duke.protobuf.data.Message.internal_static_com_duke_protobuf_data_BagSaveRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.duke.protobuf.data.BagSaveRequest.class, com.duke.protobuf.data.BagSaveRequest.Builder.class);
    }

    // Construct using com.duke.protobuf.data.BagSaveRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (bagInfoBuilder_ == null) {
        bagInfo_ = null;
      } else {
        bagInfo_ = null;
        bagInfoBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.duke.protobuf.data.Message.internal_static_com_duke_protobuf_data_BagSaveRequest_descriptor;
    }

    @java.lang.Override
    public com.duke.protobuf.data.BagSaveRequest getDefaultInstanceForType() {
      return com.duke.protobuf.data.BagSaveRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.duke.protobuf.data.BagSaveRequest build() {
      com.duke.protobuf.data.BagSaveRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.duke.protobuf.data.BagSaveRequest buildPartial() {
      com.duke.protobuf.data.BagSaveRequest result = new com.duke.protobuf.data.BagSaveRequest(this);
      if (bagInfoBuilder_ == null) {
        result.bagInfo_ = bagInfo_;
      } else {
        result.bagInfo_ = bagInfoBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.duke.protobuf.data.BagSaveRequest) {
        return mergeFrom((com.duke.protobuf.data.BagSaveRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.duke.protobuf.data.BagSaveRequest other) {
      if (other == com.duke.protobuf.data.BagSaveRequest.getDefaultInstance()) return this;
      if (other.hasBagInfo()) {
        mergeBagInfo(other.getBagInfo());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.duke.protobuf.data.BagSaveRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.duke.protobuf.data.BagSaveRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.duke.protobuf.data.NBagInfo bagInfo_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.duke.protobuf.data.NBagInfo, com.duke.protobuf.data.NBagInfo.Builder, com.duke.protobuf.data.NBagInfoOrBuilder> bagInfoBuilder_;
    /**
     * <code>.com.duke.protobuf.data.NBagInfo bagInfo = 1;</code>
     * @return Whether the bagInfo field is set.
     */
    public boolean hasBagInfo() {
      return bagInfoBuilder_ != null || bagInfo_ != null;
    }
    /**
     * <code>.com.duke.protobuf.data.NBagInfo bagInfo = 1;</code>
     * @return The bagInfo.
     */
    public com.duke.protobuf.data.NBagInfo getBagInfo() {
      if (bagInfoBuilder_ == null) {
        return bagInfo_ == null ? com.duke.protobuf.data.NBagInfo.getDefaultInstance() : bagInfo_;
      } else {
        return bagInfoBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.duke.protobuf.data.NBagInfo bagInfo = 1;</code>
     */
    public Builder setBagInfo(com.duke.protobuf.data.NBagInfo value) {
      if (bagInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        bagInfo_ = value;
        onChanged();
      } else {
        bagInfoBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.duke.protobuf.data.NBagInfo bagInfo = 1;</code>
     */
    public Builder setBagInfo(
        com.duke.protobuf.data.NBagInfo.Builder builderForValue) {
      if (bagInfoBuilder_ == null) {
        bagInfo_ = builderForValue.build();
        onChanged();
      } else {
        bagInfoBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.duke.protobuf.data.NBagInfo bagInfo = 1;</code>
     */
    public Builder mergeBagInfo(com.duke.protobuf.data.NBagInfo value) {
      if (bagInfoBuilder_ == null) {
        if (bagInfo_ != null) {
          bagInfo_ =
            com.duke.protobuf.data.NBagInfo.newBuilder(bagInfo_).mergeFrom(value).buildPartial();
        } else {
          bagInfo_ = value;
        }
        onChanged();
      } else {
        bagInfoBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.duke.protobuf.data.NBagInfo bagInfo = 1;</code>
     */
    public Builder clearBagInfo() {
      if (bagInfoBuilder_ == null) {
        bagInfo_ = null;
        onChanged();
      } else {
        bagInfo_ = null;
        bagInfoBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.duke.protobuf.data.NBagInfo bagInfo = 1;</code>
     */
    public com.duke.protobuf.data.NBagInfo.Builder getBagInfoBuilder() {
      
      onChanged();
      return getBagInfoFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.duke.protobuf.data.NBagInfo bagInfo = 1;</code>
     */
    public com.duke.protobuf.data.NBagInfoOrBuilder getBagInfoOrBuilder() {
      if (bagInfoBuilder_ != null) {
        return bagInfoBuilder_.getMessageOrBuilder();
      } else {
        return bagInfo_ == null ?
            com.duke.protobuf.data.NBagInfo.getDefaultInstance() : bagInfo_;
      }
    }
    /**
     * <code>.com.duke.protobuf.data.NBagInfo bagInfo = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.duke.protobuf.data.NBagInfo, com.duke.protobuf.data.NBagInfo.Builder, com.duke.protobuf.data.NBagInfoOrBuilder> 
        getBagInfoFieldBuilder() {
      if (bagInfoBuilder_ == null) {
        bagInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.duke.protobuf.data.NBagInfo, com.duke.protobuf.data.NBagInfo.Builder, com.duke.protobuf.data.NBagInfoOrBuilder>(
                getBagInfo(),
                getParentForChildren(),
                isClean());
        bagInfo_ = null;
      }
      return bagInfoBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.duke.protobuf.data.BagSaveRequest)
  }

  // @@protoc_insertion_point(class_scope:com.duke.protobuf.data.BagSaveRequest)
  private static final com.duke.protobuf.data.BagSaveRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.duke.protobuf.data.BagSaveRequest();
  }

  public static com.duke.protobuf.data.BagSaveRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BagSaveRequest>
      PARSER = new com.google.protobuf.AbstractParser<BagSaveRequest>() {
    @java.lang.Override
    public BagSaveRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BagSaveRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BagSaveRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BagSaveRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.duke.protobuf.data.BagSaveRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

