// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.duke.protobuf.data;

public interface BagSaveRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.duke.protobuf.data.BagSaveRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.duke.protobuf.data.NBagInfo bagInfo = 1;</code>
   * @return Whether the bagInfo field is set.
   */
  boolean hasBagInfo();
  /**
   * <code>.com.duke.protobuf.data.NBagInfo bagInfo = 1;</code>
   * @return The bagInfo.
   */
  com.duke.protobuf.data.NBagInfo getBagInfo();
  /**
   * <code>.com.duke.protobuf.data.NBagInfo bagInfo = 1;</code>
   */
  com.duke.protobuf.data.NBagInfoOrBuilder getBagInfoOrBuilder();
}
