// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.duke.protobuf.data;

public interface FriendListRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.duke.protobuf.data.FriendListRequest)
    com.google.protobuf.MessageOrBuilder {
}
