// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.duke.protobuf.data;

public interface FriendRemoveRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.duke.protobuf.data.FriendRemoveRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>int32 friendId = 2;</code>
   * @return The friendId.
   */
  int getFriendId();
}
