// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.duke.protobuf.data;

public interface ItemPurchaseRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.duke.protobuf.data.ItemPurchaseRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 shopId = 1;</code>
   * @return The shopId.
   */
  int getShopId();

  /**
   * <code>int32 shopItemId = 2;</code>
   * @return The shopItemId.
   */
  int getShopItemId();
}
