// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.duke.protobuf.data;

public interface MapCharacterEnterResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.duke.protobuf.data.MapCharacterEnterResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 mapId = 1;</code>
   * @return The mapId.
   */
  int getMapId();

  /**
   * <code>repeated .com.duke.protobuf.data.NCharacterInfo characters = 2;</code>
   */
  java.util.List<com.duke.protobuf.data.NCharacterInfo> 
      getCharactersList();
  /**
   * <code>repeated .com.duke.protobuf.data.NCharacterInfo characters = 2;</code>
   */
  com.duke.protobuf.data.NCharacterInfo getCharacters(int index);
  /**
   * <code>repeated .com.duke.protobuf.data.NCharacterInfo characters = 2;</code>
   */
  int getCharactersCount();
  /**
   * <code>repeated .com.duke.protobuf.data.NCharacterInfo characters = 2;</code>
   */
  java.util.List<? extends com.duke.protobuf.data.NCharacterInfoOrBuilder> 
      getCharactersOrBuilderList();
  /**
   * <code>repeated .com.duke.protobuf.data.NCharacterInfo characters = 2;</code>
   */
  com.duke.protobuf.data.NCharacterInfoOrBuilder getCharactersOrBuilder(
      int index);
}
