// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/message.proto

package com.duke.protobuf.data;

public interface MapCharacterLeaveResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.duke.protobuf.data.MapCharacterLeaveResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 characterId = 1;</code>
   * @return The characterId.
   */
  int getCharacterId();
}
