// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/message.proto

package com.duke.protobuf.data;

public interface MapEntitySyncRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.duke.protobuf.data.MapEntitySyncRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.duke.protobuf.data.NEntitySync entitySync = 1;</code>
   * @return Whether the entitySync field is set.
   */
  boolean hasEntitySync();
  /**
   * <code>.com.duke.protobuf.data.NEntitySync entitySync = 1;</code>
   * @return The entitySync.
   */
  com.duke.protobuf.data.NEntitySync getEntitySync();
  /**
   * <code>.com.duke.protobuf.data.NEntitySync entitySync = 1;</code>
   */
  com.duke.protobuf.data.NEntitySyncOrBuilder getEntitySyncOrBuilder();
}
