// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/message.proto

package com.duke.protobuf.data;

/**
 * Protobuf type {@code com.duke.protobuf.data.MapEntitySyncRequest}
 */
public final class MapEntitySyncRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.duke.protobuf.data.MapEntitySyncRequest)
    MapEntitySyncRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MapEntitySyncRequest.newBuilder() to construct.
  private MapEntitySyncRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MapEntitySyncRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MapEntitySyncRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MapEntitySyncRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.duke.protobuf.data.NEntitySync.Builder subBuilder = null;
            if (entitySync_ != null) {
              subBuilder = entitySync_.toBuilder();
            }
            entitySync_ = input.readMessage(com.duke.protobuf.data.NEntitySync.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(entitySync_);
              entitySync_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.duke.protobuf.data.Message.internal_static_com_duke_protobuf_data_MapEntitySyncRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.duke.protobuf.data.Message.internal_static_com_duke_protobuf_data_MapEntitySyncRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.duke.protobuf.data.MapEntitySyncRequest.class, com.duke.protobuf.data.MapEntitySyncRequest.Builder.class);
  }

  public static final int ENTITYSYNC_FIELD_NUMBER = 1;
  private com.duke.protobuf.data.NEntitySync entitySync_;
  /**
   * <code>.com.duke.protobuf.data.NEntitySync entitySync = 1;</code>
   * @return Whether the entitySync field is set.
   */
  @java.lang.Override
  public boolean hasEntitySync() {
    return entitySync_ != null;
  }
  /**
   * <code>.com.duke.protobuf.data.NEntitySync entitySync = 1;</code>
   * @return The entitySync.
   */
  @java.lang.Override
  public com.duke.protobuf.data.NEntitySync getEntitySync() {
    return entitySync_ == null ? com.duke.protobuf.data.NEntitySync.getDefaultInstance() : entitySync_;
  }
  /**
   * <code>.com.duke.protobuf.data.NEntitySync entitySync = 1;</code>
   */
  @java.lang.Override
  public com.duke.protobuf.data.NEntitySyncOrBuilder getEntitySyncOrBuilder() {
    return getEntitySync();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (entitySync_ != null) {
      output.writeMessage(1, getEntitySync());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (entitySync_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getEntitySync());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.duke.protobuf.data.MapEntitySyncRequest)) {
      return super.equals(obj);
    }
    com.duke.protobuf.data.MapEntitySyncRequest other = (com.duke.protobuf.data.MapEntitySyncRequest) obj;

    if (hasEntitySync() != other.hasEntitySync()) return false;
    if (hasEntitySync()) {
      if (!getEntitySync()
          .equals(other.getEntitySync())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasEntitySync()) {
      hash = (37 * hash) + ENTITYSYNC_FIELD_NUMBER;
      hash = (53 * hash) + getEntitySync().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.duke.protobuf.data.MapEntitySyncRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.duke.protobuf.data.MapEntitySyncRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.duke.protobuf.data.MapEntitySyncRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.duke.protobuf.data.MapEntitySyncRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.duke.protobuf.data.MapEntitySyncRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.duke.protobuf.data.MapEntitySyncRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.duke.protobuf.data.MapEntitySyncRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.duke.protobuf.data.MapEntitySyncRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.duke.protobuf.data.MapEntitySyncRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.duke.protobuf.data.MapEntitySyncRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.duke.protobuf.data.MapEntitySyncRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.duke.protobuf.data.MapEntitySyncRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.duke.protobuf.data.MapEntitySyncRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.duke.protobuf.data.MapEntitySyncRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.duke.protobuf.data.MapEntitySyncRequest)
      com.duke.protobuf.data.MapEntitySyncRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.duke.protobuf.data.Message.internal_static_com_duke_protobuf_data_MapEntitySyncRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.duke.protobuf.data.Message.internal_static_com_duke_protobuf_data_MapEntitySyncRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.duke.protobuf.data.MapEntitySyncRequest.class, com.duke.protobuf.data.MapEntitySyncRequest.Builder.class);
    }

    // Construct using com.duke.protobuf.data.MapEntitySyncRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (entitySyncBuilder_ == null) {
        entitySync_ = null;
      } else {
        entitySync_ = null;
        entitySyncBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.duke.protobuf.data.Message.internal_static_com_duke_protobuf_data_MapEntitySyncRequest_descriptor;
    }

    @java.lang.Override
    public com.duke.protobuf.data.MapEntitySyncRequest getDefaultInstanceForType() {
      return com.duke.protobuf.data.MapEntitySyncRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.duke.protobuf.data.MapEntitySyncRequest build() {
      com.duke.protobuf.data.MapEntitySyncRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.duke.protobuf.data.MapEntitySyncRequest buildPartial() {
      com.duke.protobuf.data.MapEntitySyncRequest result = new com.duke.protobuf.data.MapEntitySyncRequest(this);
      if (entitySyncBuilder_ == null) {
        result.entitySync_ = entitySync_;
      } else {
        result.entitySync_ = entitySyncBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.duke.protobuf.data.MapEntitySyncRequest) {
        return mergeFrom((com.duke.protobuf.data.MapEntitySyncRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.duke.protobuf.data.MapEntitySyncRequest other) {
      if (other == com.duke.protobuf.data.MapEntitySyncRequest.getDefaultInstance()) return this;
      if (other.hasEntitySync()) {
        mergeEntitySync(other.getEntitySync());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.duke.protobuf.data.MapEntitySyncRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.duke.protobuf.data.MapEntitySyncRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.duke.protobuf.data.NEntitySync entitySync_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.duke.protobuf.data.NEntitySync, com.duke.protobuf.data.NEntitySync.Builder, com.duke.protobuf.data.NEntitySyncOrBuilder> entitySyncBuilder_;
    /**
     * <code>.com.duke.protobuf.data.NEntitySync entitySync = 1;</code>
     * @return Whether the entitySync field is set.
     */
    public boolean hasEntitySync() {
      return entitySyncBuilder_ != null || entitySync_ != null;
    }
    /**
     * <code>.com.duke.protobuf.data.NEntitySync entitySync = 1;</code>
     * @return The entitySync.
     */
    public com.duke.protobuf.data.NEntitySync getEntitySync() {
      if (entitySyncBuilder_ == null) {
        return entitySync_ == null ? com.duke.protobuf.data.NEntitySync.getDefaultInstance() : entitySync_;
      } else {
        return entitySyncBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.duke.protobuf.data.NEntitySync entitySync = 1;</code>
     */
    public Builder setEntitySync(com.duke.protobuf.data.NEntitySync value) {
      if (entitySyncBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        entitySync_ = value;
        onChanged();
      } else {
        entitySyncBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.duke.protobuf.data.NEntitySync entitySync = 1;</code>
     */
    public Builder setEntitySync(
        com.duke.protobuf.data.NEntitySync.Builder builderForValue) {
      if (entitySyncBuilder_ == null) {
        entitySync_ = builderForValue.build();
        onChanged();
      } else {
        entitySyncBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.duke.protobuf.data.NEntitySync entitySync = 1;</code>
     */
    public Builder mergeEntitySync(com.duke.protobuf.data.NEntitySync value) {
      if (entitySyncBuilder_ == null) {
        if (entitySync_ != null) {
          entitySync_ =
            com.duke.protobuf.data.NEntitySync.newBuilder(entitySync_).mergeFrom(value).buildPartial();
        } else {
          entitySync_ = value;
        }
        onChanged();
      } else {
        entitySyncBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.duke.protobuf.data.NEntitySync entitySync = 1;</code>
     */
    public Builder clearEntitySync() {
      if (entitySyncBuilder_ == null) {
        entitySync_ = null;
        onChanged();
      } else {
        entitySync_ = null;
        entitySyncBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.duke.protobuf.data.NEntitySync entitySync = 1;</code>
     */
    public com.duke.protobuf.data.NEntitySync.Builder getEntitySyncBuilder() {
      
      onChanged();
      return getEntitySyncFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.duke.protobuf.data.NEntitySync entitySync = 1;</code>
     */
    public com.duke.protobuf.data.NEntitySyncOrBuilder getEntitySyncOrBuilder() {
      if (entitySyncBuilder_ != null) {
        return entitySyncBuilder_.getMessageOrBuilder();
      } else {
        return entitySync_ == null ?
            com.duke.protobuf.data.NEntitySync.getDefaultInstance() : entitySync_;
      }
    }
    /**
     * <code>.com.duke.protobuf.data.NEntitySync entitySync = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.duke.protobuf.data.NEntitySync, com.duke.protobuf.data.NEntitySync.Builder, com.duke.protobuf.data.NEntitySyncOrBuilder> 
        getEntitySyncFieldBuilder() {
      if (entitySyncBuilder_ == null) {
        entitySyncBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.duke.protobuf.data.NEntitySync, com.duke.protobuf.data.NEntitySync.Builder, com.duke.protobuf.data.NEntitySyncOrBuilder>(
                getEntitySync(),
                getParentForChildren(),
                isClean());
        entitySync_ = null;
      }
      return entitySyncBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.duke.protobuf.data.MapEntitySyncRequest)
  }

  // @@protoc_insertion_point(class_scope:com.duke.protobuf.data.MapEntitySyncRequest)
  private static final com.duke.protobuf.data.MapEntitySyncRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.duke.protobuf.data.MapEntitySyncRequest();
  }

  public static com.duke.protobuf.data.MapEntitySyncRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MapEntitySyncRequest>
      PARSER = new com.google.protobuf.AbstractParser<MapEntitySyncRequest>() {
    @java.lang.Override
    public MapEntitySyncRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MapEntitySyncRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MapEntitySyncRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MapEntitySyncRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.duke.protobuf.data.MapEntitySyncRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

