// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/message.proto

package com.duke.protobuf.data;

public final class Message {
  private Message() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_duke_protobuf_data_NUserInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_duke_protobuf_data_NUserInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_duke_protobuf_data_NPlayerInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_duke_protobuf_data_NPlayerInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_duke_protobuf_data_NCharacterInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_duke_protobuf_data_NCharacterInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_duke_protobuf_data_NVector3_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_duke_protobuf_data_NVector3_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_duke_protobuf_data_NEntity_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_duke_protobuf_data_NEntity_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_duke_protobuf_data_NEntitySync_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_duke_protobuf_data_NEntitySync_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_duke_protobuf_data_NetMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_duke_protobuf_data_NetMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_duke_protobuf_data_NetMessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_duke_protobuf_data_NetMessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_duke_protobuf_data_NetMessageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_duke_protobuf_data_NetMessageResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_duke_protobuf_data_UserLoginRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_duke_protobuf_data_UserLoginRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_duke_protobuf_data_UserLoginResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_duke_protobuf_data_UserLoginResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_duke_protobuf_data_UserRegisterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_duke_protobuf_data_UserRegisterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_duke_protobuf_data_UserRegisterResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_duke_protobuf_data_UserRegisterResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_duke_protobuf_data_UserCreateCharacterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_duke_protobuf_data_UserCreateCharacterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_duke_protobuf_data_UserCreateCharacterResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_duke_protobuf_data_UserCreateCharacterResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_duke_protobuf_data_UserGameEnterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_duke_protobuf_data_UserGameEnterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_duke_protobuf_data_UserGameEnterResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_duke_protobuf_data_UserGameEnterResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_duke_protobuf_data_UserGameLeaveRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_duke_protobuf_data_UserGameLeaveRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_duke_protobuf_data_UserGameLeaveResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_duke_protobuf_data_UserGameLeaveResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_duke_protobuf_data_MapCharacterEnterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_duke_protobuf_data_MapCharacterEnterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_duke_protobuf_data_MapCharacterEnterResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_duke_protobuf_data_MapCharacterEnterResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_duke_protobuf_data_MapCharacterLeaveResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_duke_protobuf_data_MapCharacterLeaveResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_duke_protobuf_data_MapEntitySyncRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_duke_protobuf_data_MapEntitySyncRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_duke_protobuf_data_MapEntitySyncResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_duke_protobuf_data_MapEntitySyncResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_duke_protobuf_data_MapTeleportRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_duke_protobuf_data_MapTeleportRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n src/main/resources/message.proto\022\026com." +
      "duke.protobuf.data\"L\n\tNUserInfo\022\n\n\002id\030\001 " +
      "\001(\005\0223\n\006player\030\002 \001(\0132#.com.duke.protobuf." +
      "data.NPlayerInfo\"U\n\013NPlayerInfo\022\n\n\002id\030\001 " +
      "\001(\005\022:\n\ncharacters\030\002 \003(\0132&.com.duke.proto" +
      "buf.data.NCharacterInfo\"\364\001\n\016NCharacterIn" +
      "fo\022\n\n\002id\030\001 \001(\005\022\013\n\003tid\030\002 \001(\005\022\014\n\004name\030\003 \001(" +
      "\t\0224\n\004type\030\004 \001(\0162&.com.duke.protobuf.data" +
      ".CHARACTER_TYPE\0226\n\005class\030\005 \001(\0162\'.com.duk" +
      "e.protobuf.data.CHARACTER_CLASS\022\r\n\005level" +
      "\030\006 \001(\005\022\r\n\005mapId\030\007 \001(\005\022/\n\006entity\030\010 \001(\0132\037." +
      "com.duke.protobuf.data.NEntity\"+\n\010NVecto" +
      "r3\022\t\n\001x\030\001 \001(\005\022\t\n\001y\030\002 \001(\005\022\t\n\001z\030\003 \001(\005\"\215\001\n\007" +
      "NEntity\022\n\n\002id\030\001 \001(\005\0222\n\010position\030\002 \001(\0132 ." +
      "com.duke.protobuf.data.NVector3\0223\n\tdirec" +
      "tion\030\003 \001(\0132 .com.duke.protobuf.data.NVec" +
      "tor3\022\r\n\005speed\030\004 \001(\005\"\326\001\n\013NEntitySync\022\n\n\002i" +
      "d\030\001 \001(\005\022?\n\005event\030\002 \001(\01620.com.duke.protob" +
      "uf.data.NEntitySync.ENTITY_EVENT\022/\n\006enti" +
      "ty\030\003 \001(\0132\037.com.duke.protobuf.data.NEntit" +
      "y\"I\n\014ENTITY_EVENT\022\010\n\004NONE\020\000\022\010\n\004IDLE\020\001\022\014\n" +
      "\010MOVE_FWD\020\002\022\r\n\tMOVE_BACK\020\003\022\010\n\004JUMP\020\004\"\206\001\n" +
      "\nNetMessage\022:\n\007Request\030\001 \001(\0132).com.duke." +
      "protobuf.data.NetMessageRequest\022<\n\010Respo" +
      "nse\030\002 \001(\0132*.com.duke.protobuf.data.NetMe" +
      "ssageResponse\"\260\004\n\021NetMessageRequest\022A\n\014u" +
      "serRegister\030\001 \001(\0132+.com.duke.protobuf.da" +
      "ta.UserRegisterRequest\022;\n\tuserLogin\030\002 \001(" +
      "\0132(.com.duke.protobuf.data.UserLoginRequ" +
      "est\022F\n\ncreateChar\030\003 \001(\01322.com.duke.proto" +
      "buf.data.UserCreateCharacterRequest\022?\n\tg" +
      "ameEnter\030\004 \001(\0132,.com.duke.protobuf.data." +
      "UserGameEnterRequest\022?\n\tgameLeave\030\005 \001(\0132" +
      ",.com.duke.protobuf.data.UserGameLeaveRe" +
      "quest\022K\n\021mapCharacterEnter\030\006 \001(\01320.com.d" +
      "uke.protobuf.data.MapCharacterEnterReque" +
      "st\022C\n\rmapEntitySync\030\010 \001(\0132,.com.duke.pro" +
      "tobuf.data.MapEntitySyncRequest\022?\n\013mapTe" +
      "leport\030\t \001(\0132*.com.duke.protobuf.data.Ma" +
      "pTeleportRequest\"\305\004\n\022NetMessageResponse\022" +
      "B\n\014userRegister\030\001 \001(\0132,.com.duke.protobu" +
      "f.data.UserRegisterResponse\022<\n\tuserLogin" +
      "\030\002 \001(\0132).com.duke.protobuf.data.UserLogi" +
      "nResponse\022G\n\ncreateChar\030\003 \001(\01323.com.duke" +
      ".protobuf.data.UserCreateCharacterRespon" +
      "se\022@\n\tgameEnter\030\004 \001(\0132-.com.duke.protobu" +
      "f.data.UserGameEnterResponse\022@\n\tgameLeav" +
      "e\030\005 \001(\0132-.com.duke.protobuf.data.UserGam" +
      "eLeaveResponse\022L\n\021mapCharacterEnter\030\006 \001(" +
      "\01321.com.duke.protobuf.data.MapCharacterE" +
      "nterResponse\022L\n\021mapCharacterLeave\030\007 \001(\0132" +
      "1.com.duke.protobuf.data.MapCharacterLea" +
      "veResponse\022D\n\rmapEntitySync\030\010 \001(\0132-.com." +
      "duke.protobuf.data.MapEntitySyncResponse" +
      "\"2\n\020UserLoginRequest\022\014\n\004user\030\001 \001(\t\022\020\n\010pa" +
      "ssward\030\002 \001(\t\"\212\001\n\021UserLoginResponse\022.\n\006re" +
      "sult\030\001 \001(\0162\036.com.duke.protobuf.data.RESU" +
      "LT\022\020\n\010errormsg\030\002 \001(\t\0223\n\010userinfo\030\003 \001(\0132!" +
      ".com.duke.protobuf.data.NUserInfo\"5\n\023Use" +
      "rRegisterRequest\022\014\n\004user\030\001 \001(\t\022\020\n\010passwa" +
      "rd\030\002 \001(\t\"X\n\024UserRegisterResponse\022.\n\006resu" +
      "lt\030\001 \001(\0162\036.com.duke.protobuf.data.RESULT" +
      "\022\020\n\010errormsg\030\002 \001(\t\"b\n\032UserCreateCharacte" +
      "rRequest\022\014\n\004name\030\001 \001(\t\0226\n\005class\030\002 \001(\0162\'." +
      "com.duke.protobuf.data.CHARACTER_CLASS\"\233" +
      "\001\n\033UserCreateCharacterResponse\022.\n\006result" +
      "\030\001 \001(\0162\036.com.duke.protobuf.data.RESULT\022\020" +
      "\n\010errormsg\030\002 \001(\t\022:\n\ncharacters\030\003 \003(\0132&.c" +
      "om.duke.protobuf.data.NCharacterInfo\",\n\024" +
      "UserGameEnterRequest\022\024\n\014characterIdx\030\001 \001" +
      "(\005\"Y\n\025UserGameEnterResponse\022.\n\006result\030\001 " +
      "\001(\0162\036.com.duke.protobuf.data.RESULT\022\020\n\010e" +
      "rrormsg\030\002 \001(\t\"\026\n\024UserGameLeaveRequest\"Y\n" +
      "\025UserGameLeaveResponse\022.\n\006result\030\001 \001(\0162\036" +
      ".com.duke.protobuf.data.RESULT\022\020\n\010errorm" +
      "sg\030\002 \001(\t\")\n\030MapCharacterEnterRequest\022\r\n\005" +
      "mapId\030\001 \001(\005\"f\n\031MapCharacterEnterResponse" +
      "\022\r\n\005mapId\030\001 \001(\005\022:\n\ncharacters\030\002 \003(\0132&.co" +
      "m.duke.protobuf.data.NCharacterInfo\"0\n\031M" +
      "apCharacterLeaveResponse\022\023\n\013characterId\030" +
      "\001 \001(\005\"O\n\024MapEntitySyncRequest\0227\n\nentityS" +
      "ync\030\001 \001(\0132#.com.duke.protobuf.data.NEnti" +
      "tySync\"Q\n\025MapEntitySyncResponse\0228\n\013entit" +
      "ySyncs\030\002 \003(\0132#.com.duke.protobuf.data.NE" +
      "ntitySync\"*\n\022MapTeleportRequest\022\024\n\014telep" +
      "orterId\030\001 \001(\005*!\n\006RESULT\022\013\n\007SUCCESS\020\000\022\n\n\006" +
      "FAILED\020\001*2\n\016CHARACTER_TYPE\022\n\n\006Player\020\000\022\007" +
      "\n\003NPC\020\001\022\013\n\007Monster\020\002*@\n\017CHARACTER_CLASS\022" +
      "\010\n\004NONE\020\000\022\013\n\007WARRIOR\020\001\022\n\n\006WIZARD\020\002\022\n\n\006AR" +
      "CHER\020\003*%\n\017CHARACTER_STATE\022\010\n\004IDLE\020\000\022\010\n\004M" +
      "OVE\020\001B\005P\001\370\001\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_duke_protobuf_data_NUserInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_duke_protobuf_data_NUserInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_duke_protobuf_data_NUserInfo_descriptor,
        new java.lang.String[] { "Id", "Player", });
    internal_static_com_duke_protobuf_data_NPlayerInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_duke_protobuf_data_NPlayerInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_duke_protobuf_data_NPlayerInfo_descriptor,
        new java.lang.String[] { "Id", "Characters", });
    internal_static_com_duke_protobuf_data_NCharacterInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_duke_protobuf_data_NCharacterInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_duke_protobuf_data_NCharacterInfo_descriptor,
        new java.lang.String[] { "Id", "Tid", "Name", "Type", "Class_", "Level", "MapId", "Entity", });
    internal_static_com_duke_protobuf_data_NVector3_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_duke_protobuf_data_NVector3_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_duke_protobuf_data_NVector3_descriptor,
        new java.lang.String[] { "X", "Y", "Z", });
    internal_static_com_duke_protobuf_data_NEntity_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_duke_protobuf_data_NEntity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_duke_protobuf_data_NEntity_descriptor,
        new java.lang.String[] { "Id", "Position", "Direction", "Speed", });
    internal_static_com_duke_protobuf_data_NEntitySync_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_duke_protobuf_data_NEntitySync_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_duke_protobuf_data_NEntitySync_descriptor,
        new java.lang.String[] { "Id", "Event", "Entity", });
    internal_static_com_duke_protobuf_data_NetMessage_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_duke_protobuf_data_NetMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_duke_protobuf_data_NetMessage_descriptor,
        new java.lang.String[] { "Request", "Response", });
    internal_static_com_duke_protobuf_data_NetMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_duke_protobuf_data_NetMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_duke_protobuf_data_NetMessageRequest_descriptor,
        new java.lang.String[] { "UserRegister", "UserLogin", "CreateChar", "GameEnter", "GameLeave", "MapCharacterEnter", "MapEntitySync", "MapTeleport", });
    internal_static_com_duke_protobuf_data_NetMessageResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_com_duke_protobuf_data_NetMessageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_duke_protobuf_data_NetMessageResponse_descriptor,
        new java.lang.String[] { "UserRegister", "UserLogin", "CreateChar", "GameEnter", "GameLeave", "MapCharacterEnter", "MapCharacterLeave", "MapEntitySync", });
    internal_static_com_duke_protobuf_data_UserLoginRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_com_duke_protobuf_data_UserLoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_duke_protobuf_data_UserLoginRequest_descriptor,
        new java.lang.String[] { "User", "Passward", });
    internal_static_com_duke_protobuf_data_UserLoginResponse_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_com_duke_protobuf_data_UserLoginResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_duke_protobuf_data_UserLoginResponse_descriptor,
        new java.lang.String[] { "Result", "Errormsg", "Userinfo", });
    internal_static_com_duke_protobuf_data_UserRegisterRequest_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_com_duke_protobuf_data_UserRegisterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_duke_protobuf_data_UserRegisterRequest_descriptor,
        new java.lang.String[] { "User", "Passward", });
    internal_static_com_duke_protobuf_data_UserRegisterResponse_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_com_duke_protobuf_data_UserRegisterResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_duke_protobuf_data_UserRegisterResponse_descriptor,
        new java.lang.String[] { "Result", "Errormsg", });
    internal_static_com_duke_protobuf_data_UserCreateCharacterRequest_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_com_duke_protobuf_data_UserCreateCharacterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_duke_protobuf_data_UserCreateCharacterRequest_descriptor,
        new java.lang.String[] { "Name", "Class_", });
    internal_static_com_duke_protobuf_data_UserCreateCharacterResponse_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_com_duke_protobuf_data_UserCreateCharacterResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_duke_protobuf_data_UserCreateCharacterResponse_descriptor,
        new java.lang.String[] { "Result", "Errormsg", "Characters", });
    internal_static_com_duke_protobuf_data_UserGameEnterRequest_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_com_duke_protobuf_data_UserGameEnterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_duke_protobuf_data_UserGameEnterRequest_descriptor,
        new java.lang.String[] { "CharacterIdx", });
    internal_static_com_duke_protobuf_data_UserGameEnterResponse_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_com_duke_protobuf_data_UserGameEnterResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_duke_protobuf_data_UserGameEnterResponse_descriptor,
        new java.lang.String[] { "Result", "Errormsg", });
    internal_static_com_duke_protobuf_data_UserGameLeaveRequest_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_com_duke_protobuf_data_UserGameLeaveRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_duke_protobuf_data_UserGameLeaveRequest_descriptor,
        new java.lang.String[] { });
    internal_static_com_duke_protobuf_data_UserGameLeaveResponse_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_com_duke_protobuf_data_UserGameLeaveResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_duke_protobuf_data_UserGameLeaveResponse_descriptor,
        new java.lang.String[] { "Result", "Errormsg", });
    internal_static_com_duke_protobuf_data_MapCharacterEnterRequest_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_com_duke_protobuf_data_MapCharacterEnterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_duke_protobuf_data_MapCharacterEnterRequest_descriptor,
        new java.lang.String[] { "MapId", });
    internal_static_com_duke_protobuf_data_MapCharacterEnterResponse_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_com_duke_protobuf_data_MapCharacterEnterResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_duke_protobuf_data_MapCharacterEnterResponse_descriptor,
        new java.lang.String[] { "MapId", "Characters", });
    internal_static_com_duke_protobuf_data_MapCharacterLeaveResponse_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_com_duke_protobuf_data_MapCharacterLeaveResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_duke_protobuf_data_MapCharacterLeaveResponse_descriptor,
        new java.lang.String[] { "CharacterId", });
    internal_static_com_duke_protobuf_data_MapEntitySyncRequest_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_com_duke_protobuf_data_MapEntitySyncRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_duke_protobuf_data_MapEntitySyncRequest_descriptor,
        new java.lang.String[] { "EntitySync", });
    internal_static_com_duke_protobuf_data_MapEntitySyncResponse_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_com_duke_protobuf_data_MapEntitySyncResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_duke_protobuf_data_MapEntitySyncResponse_descriptor,
        new java.lang.String[] { "EntitySyncs", });
    internal_static_com_duke_protobuf_data_MapTeleportRequest_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_com_duke_protobuf_data_MapTeleportRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_duke_protobuf_data_MapTeleportRequest_descriptor,
        new java.lang.String[] { "TeleporterId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
