// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.duke.protobuf.data;

/**
 * <pre>
 * 背包数据
 * </pre>
 *
 * Protobuf type {@code com.duke.protobuf.data.NBagInfo}
 */
public final class NBagInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.duke.protobuf.data.NBagInfo)
    NBagInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use NBagInfo.newBuilder() to construct.
  private NBagInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private NBagInfo() {
    items_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new NBagInfo();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private NBagInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            unlocked_ = input.readInt32();
            break;
          }
          case 18: {

            items_ = input.readBytes();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.duke.protobuf.data.Message.internal_static_com_duke_protobuf_data_NBagInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.duke.protobuf.data.Message.internal_static_com_duke_protobuf_data_NBagInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.duke.protobuf.data.NBagInfo.class, com.duke.protobuf.data.NBagInfo.Builder.class);
  }

  public static final int UNLOCKED_FIELD_NUMBER = 1;
  private int unlocked_;
  /**
   * <pre>
   * 解锁了多少个格子
   * </pre>
   *
   * <code>int32 unlocked = 1;</code>
   * @return The unlocked.
   */
  @java.lang.Override
  public int getUnlocked() {
    return unlocked_;
  }

  public static final int ITEMS_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString items_;
  /**
   * <pre>
   * 具体道具数据（二进制）
   * </pre>
   *
   * <code>bytes items = 2;</code>
   * @return The items.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getItems() {
    return items_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (unlocked_ != 0) {
      output.writeInt32(1, unlocked_);
    }
    if (!items_.isEmpty()) {
      output.writeBytes(2, items_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (unlocked_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, unlocked_);
    }
    if (!items_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, items_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.duke.protobuf.data.NBagInfo)) {
      return super.equals(obj);
    }
    com.duke.protobuf.data.NBagInfo other = (com.duke.protobuf.data.NBagInfo) obj;

    if (getUnlocked()
        != other.getUnlocked()) return false;
    if (!getItems()
        .equals(other.getItems())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + UNLOCKED_FIELD_NUMBER;
    hash = (53 * hash) + getUnlocked();
    hash = (37 * hash) + ITEMS_FIELD_NUMBER;
    hash = (53 * hash) + getItems().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.duke.protobuf.data.NBagInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.duke.protobuf.data.NBagInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.duke.protobuf.data.NBagInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.duke.protobuf.data.NBagInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.duke.protobuf.data.NBagInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.duke.protobuf.data.NBagInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.duke.protobuf.data.NBagInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.duke.protobuf.data.NBagInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.duke.protobuf.data.NBagInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.duke.protobuf.data.NBagInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.duke.protobuf.data.NBagInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.duke.protobuf.data.NBagInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.duke.protobuf.data.NBagInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 背包数据
   * </pre>
   *
   * Protobuf type {@code com.duke.protobuf.data.NBagInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.duke.protobuf.data.NBagInfo)
      com.duke.protobuf.data.NBagInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.duke.protobuf.data.Message.internal_static_com_duke_protobuf_data_NBagInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.duke.protobuf.data.Message.internal_static_com_duke_protobuf_data_NBagInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.duke.protobuf.data.NBagInfo.class, com.duke.protobuf.data.NBagInfo.Builder.class);
    }

    // Construct using com.duke.protobuf.data.NBagInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      unlocked_ = 0;

      items_ = com.google.protobuf.ByteString.EMPTY;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.duke.protobuf.data.Message.internal_static_com_duke_protobuf_data_NBagInfo_descriptor;
    }

    @java.lang.Override
    public com.duke.protobuf.data.NBagInfo getDefaultInstanceForType() {
      return com.duke.protobuf.data.NBagInfo.getDefaultInstance();
    }

    @java.lang.Override
    public com.duke.protobuf.data.NBagInfo build() {
      com.duke.protobuf.data.NBagInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.duke.protobuf.data.NBagInfo buildPartial() {
      com.duke.protobuf.data.NBagInfo result = new com.duke.protobuf.data.NBagInfo(this);
      result.unlocked_ = unlocked_;
      result.items_ = items_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.duke.protobuf.data.NBagInfo) {
        return mergeFrom((com.duke.protobuf.data.NBagInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.duke.protobuf.data.NBagInfo other) {
      if (other == com.duke.protobuf.data.NBagInfo.getDefaultInstance()) return this;
      if (other.getUnlocked() != 0) {
        setUnlocked(other.getUnlocked());
      }
      if (other.getItems() != com.google.protobuf.ByteString.EMPTY) {
        setItems(other.getItems());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.duke.protobuf.data.NBagInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.duke.protobuf.data.NBagInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int unlocked_ ;
    /**
     * <pre>
     * 解锁了多少个格子
     * </pre>
     *
     * <code>int32 unlocked = 1;</code>
     * @return The unlocked.
     */
    @java.lang.Override
    public int getUnlocked() {
      return unlocked_;
    }
    /**
     * <pre>
     * 解锁了多少个格子
     * </pre>
     *
     * <code>int32 unlocked = 1;</code>
     * @param value The unlocked to set.
     * @return This builder for chaining.
     */
    public Builder setUnlocked(int value) {
      
      unlocked_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 解锁了多少个格子
     * </pre>
     *
     * <code>int32 unlocked = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUnlocked() {
      
      unlocked_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString items_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * 具体道具数据（二进制）
     * </pre>
     *
     * <code>bytes items = 2;</code>
     * @return The items.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getItems() {
      return items_;
    }
    /**
     * <pre>
     * 具体道具数据（二进制）
     * </pre>
     *
     * <code>bytes items = 2;</code>
     * @param value The items to set.
     * @return This builder for chaining.
     */
    public Builder setItems(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      items_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 具体道具数据（二进制）
     * </pre>
     *
     * <code>bytes items = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearItems() {
      
      items_ = getDefaultInstance().getItems();
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.duke.protobuf.data.NBagInfo)
  }

  // @@protoc_insertion_point(class_scope:com.duke.protobuf.data.NBagInfo)
  private static final com.duke.protobuf.data.NBagInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.duke.protobuf.data.NBagInfo();
  }

  public static com.duke.protobuf.data.NBagInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NBagInfo>
      PARSER = new com.google.protobuf.AbstractParser<NBagInfo>() {
    @java.lang.Override
    public NBagInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new NBagInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<NBagInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<NBagInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.duke.protobuf.data.NBagInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

