// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.duke.protobuf.data;

public interface NCharacterInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.duke.protobuf.data.NCharacterInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 数据库ID
   * </pre>
   *
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <pre>
   * 配置表ID
   * </pre>
   *
   * <code>int32 configId = 2;</code>
   * @return The configId.
   */
  int getConfigId();

  /**
   * <pre>
   * 实体ID
   * </pre>
   *
   * <code>int32 entityId = 3;</code>
   * @return The entityId.
   */
  int getEntityId();

  /**
   * <pre>
   * 名字
   * </pre>
   *
   * <code>string name = 4;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * 名字
   * </pre>
   *
   * <code>string name = 4;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.com.duke.protobuf.data.CHARACTER_TYPE type = 5;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.com.duke.protobuf.data.CHARACTER_TYPE type = 5;</code>
   * @return The type.
   */
  com.duke.protobuf.data.CHARACTER_TYPE getType();

  /**
   * <code>.com.duke.protobuf.data.CHARACTER_CLASS class = 6;</code>
   * @return The enum numeric value on the wire for class.
   */
  int getClass_Value();
  /**
   * <code>.com.duke.protobuf.data.CHARACTER_CLASS class = 6;</code>
   * @return The class.
   */
  com.duke.protobuf.data.CHARACTER_CLASS getClass_();

  /**
   * <code>int32 level = 7;</code>
   * @return The level.
   */
  int getLevel();

  /**
   * <code>int32 mapId = 8;</code>
   * @return The mapId.
   */
  int getMapId();

  /**
   * <code>.com.duke.protobuf.data.NEntity entity = 9;</code>
   * @return Whether the entity field is set.
   */
  boolean hasEntity();
  /**
   * <code>.com.duke.protobuf.data.NEntity entity = 9;</code>
   * @return The entity.
   */
  com.duke.protobuf.data.NEntity getEntity();
  /**
   * <code>.com.duke.protobuf.data.NEntity entity = 9;</code>
   */
  com.duke.protobuf.data.NEntityOrBuilder getEntityOrBuilder();

  /**
   * <code>int64 carriedMoney = 10;</code>
   * @return The carriedMoney.
   */
  long getCarriedMoney();

  /**
   * <pre>
   * 道具信息
   * </pre>
   *
   * <code>repeated .com.duke.protobuf.data.NItemInfo items = 11;</code>
   */
  java.util.List<com.duke.protobuf.data.NItemInfo> 
      getItemsList();
  /**
   * <pre>
   * 道具信息
   * </pre>
   *
   * <code>repeated .com.duke.protobuf.data.NItemInfo items = 11;</code>
   */
  com.duke.protobuf.data.NItemInfo getItems(int index);
  /**
   * <pre>
   * 道具信息
   * </pre>
   *
   * <code>repeated .com.duke.protobuf.data.NItemInfo items = 11;</code>
   */
  int getItemsCount();
  /**
   * <pre>
   * 道具信息
   * </pre>
   *
   * <code>repeated .com.duke.protobuf.data.NItemInfo items = 11;</code>
   */
  java.util.List<? extends com.duke.protobuf.data.NItemInfoOrBuilder> 
      getItemsOrBuilderList();
  /**
   * <pre>
   * 道具信息
   * </pre>
   *
   * <code>repeated .com.duke.protobuf.data.NItemInfo items = 11;</code>
   */
  com.duke.protobuf.data.NItemInfoOrBuilder getItemsOrBuilder(
      int index);

  /**
   * <pre>
   * 背包信息
   * </pre>
   *
   * <code>.com.duke.protobuf.data.NBagInfo bag = 12;</code>
   * @return Whether the bag field is set.
   */
  boolean hasBag();
  /**
   * <pre>
   * 背包信息
   * </pre>
   *
   * <code>.com.duke.protobuf.data.NBagInfo bag = 12;</code>
   * @return The bag.
   */
  com.duke.protobuf.data.NBagInfo getBag();
  /**
   * <pre>
   * 背包信息
   * </pre>
   *
   * <code>.com.duke.protobuf.data.NBagInfo bag = 12;</code>
   */
  com.duke.protobuf.data.NBagInfoOrBuilder getBagOrBuilder();

  /**
   * <pre>
   * 装备信息（字节数组形式）
   * </pre>
   *
   * <code>bytes equips = 13;</code>
   * @return The equips.
   */
  com.google.protobuf.ByteString getEquips();

  /**
   * <pre>
   * 任务列表信息
   * </pre>
   *
   * <code>repeated .com.duke.protobuf.data.NQuestInfo quests = 14;</code>
   */
  java.util.List<com.duke.protobuf.data.NQuestInfo> 
      getQuestsList();
  /**
   * <pre>
   * 任务列表信息
   * </pre>
   *
   * <code>repeated .com.duke.protobuf.data.NQuestInfo quests = 14;</code>
   */
  com.duke.protobuf.data.NQuestInfo getQuests(int index);
  /**
   * <pre>
   * 任务列表信息
   * </pre>
   *
   * <code>repeated .com.duke.protobuf.data.NQuestInfo quests = 14;</code>
   */
  int getQuestsCount();
  /**
   * <pre>
   * 任务列表信息
   * </pre>
   *
   * <code>repeated .com.duke.protobuf.data.NQuestInfo quests = 14;</code>
   */
  java.util.List<? extends com.duke.protobuf.data.NQuestInfoOrBuilder> 
      getQuestsOrBuilderList();
  /**
   * <pre>
   * 任务列表信息
   * </pre>
   *
   * <code>repeated .com.duke.protobuf.data.NQuestInfo quests = 14;</code>
   */
  com.duke.protobuf.data.NQuestInfoOrBuilder getQuestsOrBuilder(
      int index);

  /**
   * <pre>
   * 好友信息
   * </pre>
   *
   * <code>repeated .com.duke.protobuf.data.NFriendInfo friends = 15;</code>
   */
  java.util.List<com.duke.protobuf.data.NFriendInfo> 
      getFriendsList();
  /**
   * <pre>
   * 好友信息
   * </pre>
   *
   * <code>repeated .com.duke.protobuf.data.NFriendInfo friends = 15;</code>
   */
  com.duke.protobuf.data.NFriendInfo getFriends(int index);
  /**
   * <pre>
   * 好友信息
   * </pre>
   *
   * <code>repeated .com.duke.protobuf.data.NFriendInfo friends = 15;</code>
   */
  int getFriendsCount();
  /**
   * <pre>
   * 好友信息
   * </pre>
   *
   * <code>repeated .com.duke.protobuf.data.NFriendInfo friends = 15;</code>
   */
  java.util.List<? extends com.duke.protobuf.data.NFriendInfoOrBuilder> 
      getFriendsOrBuilderList();
  /**
   * <pre>
   * 好友信息
   * </pre>
   *
   * <code>repeated .com.duke.protobuf.data.NFriendInfo friends = 15;</code>
   */
  com.duke.protobuf.data.NFriendInfoOrBuilder getFriendsOrBuilder(
      int index);
}
