// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.duke.protobuf.data;

public interface NCharacterInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.duke.protobuf.data.NCharacterInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>int32 tid = 2;</code>
   * @return The tid.
   */
  int getTid();

  /**
   * <code>string name = 3;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 3;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.com.duke.protobuf.data.CHARACTER_TYPE type = 4;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.com.duke.protobuf.data.CHARACTER_TYPE type = 4;</code>
   * @return The type.
   */
  com.duke.protobuf.data.CHARACTER_TYPE getType();

  /**
   * <code>.com.duke.protobuf.data.CHARACTER_CLASS class = 5;</code>
   * @return The enum numeric value on the wire for class.
   */
  int getClass_Value();
  /**
   * <code>.com.duke.protobuf.data.CHARACTER_CLASS class = 5;</code>
   * @return The class.
   */
  com.duke.protobuf.data.CHARACTER_CLASS getClass_();

  /**
   * <code>int32 level = 6;</code>
   * @return The level.
   */
  int getLevel();

  /**
   * <code>int32 mapId = 7;</code>
   * @return The mapId.
   */
  int getMapId();

  /**
   * <code>.com.duke.protobuf.data.NEntity entity = 8;</code>
   * @return Whether the entity field is set.
   */
  boolean hasEntity();
  /**
   * <code>.com.duke.protobuf.data.NEntity entity = 8;</code>
   * @return The entity.
   */
  com.duke.protobuf.data.NEntity getEntity();
  /**
   * <code>.com.duke.protobuf.data.NEntity entity = 8;</code>
   */
  com.duke.protobuf.data.NEntityOrBuilder getEntityOrBuilder();

  /**
   * <code>int64 carriedMoney = 9;</code>
   * @return The carriedMoney.
   */
  long getCarriedMoney();

  /**
   * <code>repeated .com.duke.protobuf.data.NItemInfo items = 10;</code>
   */
  java.util.List<com.duke.protobuf.data.NItemInfo> 
      getItemsList();
  /**
   * <code>repeated .com.duke.protobuf.data.NItemInfo items = 10;</code>
   */
  com.duke.protobuf.data.NItemInfo getItems(int index);
  /**
   * <code>repeated .com.duke.protobuf.data.NItemInfo items = 10;</code>
   */
  int getItemsCount();
  /**
   * <code>repeated .com.duke.protobuf.data.NItemInfo items = 10;</code>
   */
  java.util.List<? extends com.duke.protobuf.data.NItemInfoOrBuilder> 
      getItemsOrBuilderList();
  /**
   * <code>repeated .com.duke.protobuf.data.NItemInfo items = 10;</code>
   */
  com.duke.protobuf.data.NItemInfoOrBuilder getItemsOrBuilder(
      int index);

  /**
   * <code>.com.duke.protobuf.data.NBagInfo bag = 11;</code>
   * @return Whether the bag field is set.
   */
  boolean hasBag();
  /**
   * <code>.com.duke.protobuf.data.NBagInfo bag = 11;</code>
   * @return The bag.
   */
  com.duke.protobuf.data.NBagInfo getBag();
  /**
   * <code>.com.duke.protobuf.data.NBagInfo bag = 11;</code>
   */
  com.duke.protobuf.data.NBagInfoOrBuilder getBagOrBuilder();
}
