// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/message.proto

package com.duke.protobuf.data;

/**
 * Protobuf type {@code com.duke.protobuf.data.NetMessageRequest}
 */
public final class NetMessageRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.duke.protobuf.data.NetMessageRequest)
    NetMessageRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use NetMessageRequest.newBuilder() to construct.
  private NetMessageRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private NetMessageRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new NetMessageRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private NetMessageRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.duke.protobuf.data.UserRegisterRequest.Builder subBuilder = null;
            if (userRegister_ != null) {
              subBuilder = userRegister_.toBuilder();
            }
            userRegister_ = input.readMessage(com.duke.protobuf.data.UserRegisterRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(userRegister_);
              userRegister_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.duke.protobuf.data.UserLoginRequest.Builder subBuilder = null;
            if (userLogin_ != null) {
              subBuilder = userLogin_.toBuilder();
            }
            userLogin_ = input.readMessage(com.duke.protobuf.data.UserLoginRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(userLogin_);
              userLogin_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            com.duke.protobuf.data.UserCreateCharacterRequest.Builder subBuilder = null;
            if (createChar_ != null) {
              subBuilder = createChar_.toBuilder();
            }
            createChar_ = input.readMessage(com.duke.protobuf.data.UserCreateCharacterRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(createChar_);
              createChar_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            com.duke.protobuf.data.UserGameEnterRequest.Builder subBuilder = null;
            if (gameEnter_ != null) {
              subBuilder = gameEnter_.toBuilder();
            }
            gameEnter_ = input.readMessage(com.duke.protobuf.data.UserGameEnterRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(gameEnter_);
              gameEnter_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            com.duke.protobuf.data.UserGameLeaveRequest.Builder subBuilder = null;
            if (gameLeave_ != null) {
              subBuilder = gameLeave_.toBuilder();
            }
            gameLeave_ = input.readMessage(com.duke.protobuf.data.UserGameLeaveRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(gameLeave_);
              gameLeave_ = subBuilder.buildPartial();
            }

            break;
          }
          case 50: {
            com.duke.protobuf.data.MapCharacterEnterRequest.Builder subBuilder = null;
            if (mapCharacterEnter_ != null) {
              subBuilder = mapCharacterEnter_.toBuilder();
            }
            mapCharacterEnter_ = input.readMessage(com.duke.protobuf.data.MapCharacterEnterRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(mapCharacterEnter_);
              mapCharacterEnter_ = subBuilder.buildPartial();
            }

            break;
          }
          case 66: {
            com.duke.protobuf.data.MapEntitySyncRequest.Builder subBuilder = null;
            if (mapEntitySync_ != null) {
              subBuilder = mapEntitySync_.toBuilder();
            }
            mapEntitySync_ = input.readMessage(com.duke.protobuf.data.MapEntitySyncRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(mapEntitySync_);
              mapEntitySync_ = subBuilder.buildPartial();
            }

            break;
          }
          case 74: {
            com.duke.protobuf.data.MapTeleportRequest.Builder subBuilder = null;
            if (mapTeleport_ != null) {
              subBuilder = mapTeleport_.toBuilder();
            }
            mapTeleport_ = input.readMessage(com.duke.protobuf.data.MapTeleportRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(mapTeleport_);
              mapTeleport_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.duke.protobuf.data.Message.internal_static_com_duke_protobuf_data_NetMessageRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.duke.protobuf.data.Message.internal_static_com_duke_protobuf_data_NetMessageRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.duke.protobuf.data.NetMessageRequest.class, com.duke.protobuf.data.NetMessageRequest.Builder.class);
  }

  public static final int USERREGISTER_FIELD_NUMBER = 1;
  private com.duke.protobuf.data.UserRegisterRequest userRegister_;
  /**
   * <code>.com.duke.protobuf.data.UserRegisterRequest userRegister = 1;</code>
   * @return Whether the userRegister field is set.
   */
  @java.lang.Override
  public boolean hasUserRegister() {
    return userRegister_ != null;
  }
  /**
   * <code>.com.duke.protobuf.data.UserRegisterRequest userRegister = 1;</code>
   * @return The userRegister.
   */
  @java.lang.Override
  public com.duke.protobuf.data.UserRegisterRequest getUserRegister() {
    return userRegister_ == null ? com.duke.protobuf.data.UserRegisterRequest.getDefaultInstance() : userRegister_;
  }
  /**
   * <code>.com.duke.protobuf.data.UserRegisterRequest userRegister = 1;</code>
   */
  @java.lang.Override
  public com.duke.protobuf.data.UserRegisterRequestOrBuilder getUserRegisterOrBuilder() {
    return getUserRegister();
  }

  public static final int USERLOGIN_FIELD_NUMBER = 2;
  private com.duke.protobuf.data.UserLoginRequest userLogin_;
  /**
   * <code>.com.duke.protobuf.data.UserLoginRequest userLogin = 2;</code>
   * @return Whether the userLogin field is set.
   */
  @java.lang.Override
  public boolean hasUserLogin() {
    return userLogin_ != null;
  }
  /**
   * <code>.com.duke.protobuf.data.UserLoginRequest userLogin = 2;</code>
   * @return The userLogin.
   */
  @java.lang.Override
  public com.duke.protobuf.data.UserLoginRequest getUserLogin() {
    return userLogin_ == null ? com.duke.protobuf.data.UserLoginRequest.getDefaultInstance() : userLogin_;
  }
  /**
   * <code>.com.duke.protobuf.data.UserLoginRequest userLogin = 2;</code>
   */
  @java.lang.Override
  public com.duke.protobuf.data.UserLoginRequestOrBuilder getUserLoginOrBuilder() {
    return getUserLogin();
  }

  public static final int CREATECHAR_FIELD_NUMBER = 3;
  private com.duke.protobuf.data.UserCreateCharacterRequest createChar_;
  /**
   * <code>.com.duke.protobuf.data.UserCreateCharacterRequest createChar = 3;</code>
   * @return Whether the createChar field is set.
   */
  @java.lang.Override
  public boolean hasCreateChar() {
    return createChar_ != null;
  }
  /**
   * <code>.com.duke.protobuf.data.UserCreateCharacterRequest createChar = 3;</code>
   * @return The createChar.
   */
  @java.lang.Override
  public com.duke.protobuf.data.UserCreateCharacterRequest getCreateChar() {
    return createChar_ == null ? com.duke.protobuf.data.UserCreateCharacterRequest.getDefaultInstance() : createChar_;
  }
  /**
   * <code>.com.duke.protobuf.data.UserCreateCharacterRequest createChar = 3;</code>
   */
  @java.lang.Override
  public com.duke.protobuf.data.UserCreateCharacterRequestOrBuilder getCreateCharOrBuilder() {
    return getCreateChar();
  }

  public static final int GAMEENTER_FIELD_NUMBER = 4;
  private com.duke.protobuf.data.UserGameEnterRequest gameEnter_;
  /**
   * <code>.com.duke.protobuf.data.UserGameEnterRequest gameEnter = 4;</code>
   * @return Whether the gameEnter field is set.
   */
  @java.lang.Override
  public boolean hasGameEnter() {
    return gameEnter_ != null;
  }
  /**
   * <code>.com.duke.protobuf.data.UserGameEnterRequest gameEnter = 4;</code>
   * @return The gameEnter.
   */
  @java.lang.Override
  public com.duke.protobuf.data.UserGameEnterRequest getGameEnter() {
    return gameEnter_ == null ? com.duke.protobuf.data.UserGameEnterRequest.getDefaultInstance() : gameEnter_;
  }
  /**
   * <code>.com.duke.protobuf.data.UserGameEnterRequest gameEnter = 4;</code>
   */
  @java.lang.Override
  public com.duke.protobuf.data.UserGameEnterRequestOrBuilder getGameEnterOrBuilder() {
    return getGameEnter();
  }

  public static final int GAMELEAVE_FIELD_NUMBER = 5;
  private com.duke.protobuf.data.UserGameLeaveRequest gameLeave_;
  /**
   * <code>.com.duke.protobuf.data.UserGameLeaveRequest gameLeave = 5;</code>
   * @return Whether the gameLeave field is set.
   */
  @java.lang.Override
  public boolean hasGameLeave() {
    return gameLeave_ != null;
  }
  /**
   * <code>.com.duke.protobuf.data.UserGameLeaveRequest gameLeave = 5;</code>
   * @return The gameLeave.
   */
  @java.lang.Override
  public com.duke.protobuf.data.UserGameLeaveRequest getGameLeave() {
    return gameLeave_ == null ? com.duke.protobuf.data.UserGameLeaveRequest.getDefaultInstance() : gameLeave_;
  }
  /**
   * <code>.com.duke.protobuf.data.UserGameLeaveRequest gameLeave = 5;</code>
   */
  @java.lang.Override
  public com.duke.protobuf.data.UserGameLeaveRequestOrBuilder getGameLeaveOrBuilder() {
    return getGameLeave();
  }

  public static final int MAPCHARACTERENTER_FIELD_NUMBER = 6;
  private com.duke.protobuf.data.MapCharacterEnterRequest mapCharacterEnter_;
  /**
   * <code>.com.duke.protobuf.data.MapCharacterEnterRequest mapCharacterEnter = 6;</code>
   * @return Whether the mapCharacterEnter field is set.
   */
  @java.lang.Override
  public boolean hasMapCharacterEnter() {
    return mapCharacterEnter_ != null;
  }
  /**
   * <code>.com.duke.protobuf.data.MapCharacterEnterRequest mapCharacterEnter = 6;</code>
   * @return The mapCharacterEnter.
   */
  @java.lang.Override
  public com.duke.protobuf.data.MapCharacterEnterRequest getMapCharacterEnter() {
    return mapCharacterEnter_ == null ? com.duke.protobuf.data.MapCharacterEnterRequest.getDefaultInstance() : mapCharacterEnter_;
  }
  /**
   * <code>.com.duke.protobuf.data.MapCharacterEnterRequest mapCharacterEnter = 6;</code>
   */
  @java.lang.Override
  public com.duke.protobuf.data.MapCharacterEnterRequestOrBuilder getMapCharacterEnterOrBuilder() {
    return getMapCharacterEnter();
  }

  public static final int MAPENTITYSYNC_FIELD_NUMBER = 8;
  private com.duke.protobuf.data.MapEntitySyncRequest mapEntitySync_;
  /**
   * <code>.com.duke.protobuf.data.MapEntitySyncRequest mapEntitySync = 8;</code>
   * @return Whether the mapEntitySync field is set.
   */
  @java.lang.Override
  public boolean hasMapEntitySync() {
    return mapEntitySync_ != null;
  }
  /**
   * <code>.com.duke.protobuf.data.MapEntitySyncRequest mapEntitySync = 8;</code>
   * @return The mapEntitySync.
   */
  @java.lang.Override
  public com.duke.protobuf.data.MapEntitySyncRequest getMapEntitySync() {
    return mapEntitySync_ == null ? com.duke.protobuf.data.MapEntitySyncRequest.getDefaultInstance() : mapEntitySync_;
  }
  /**
   * <code>.com.duke.protobuf.data.MapEntitySyncRequest mapEntitySync = 8;</code>
   */
  @java.lang.Override
  public com.duke.protobuf.data.MapEntitySyncRequestOrBuilder getMapEntitySyncOrBuilder() {
    return getMapEntitySync();
  }

  public static final int MAPTELEPORT_FIELD_NUMBER = 9;
  private com.duke.protobuf.data.MapTeleportRequest mapTeleport_;
  /**
   * <code>.com.duke.protobuf.data.MapTeleportRequest mapTeleport = 9;</code>
   * @return Whether the mapTeleport field is set.
   */
  @java.lang.Override
  public boolean hasMapTeleport() {
    return mapTeleport_ != null;
  }
  /**
   * <code>.com.duke.protobuf.data.MapTeleportRequest mapTeleport = 9;</code>
   * @return The mapTeleport.
   */
  @java.lang.Override
  public com.duke.protobuf.data.MapTeleportRequest getMapTeleport() {
    return mapTeleport_ == null ? com.duke.protobuf.data.MapTeleportRequest.getDefaultInstance() : mapTeleport_;
  }
  /**
   * <code>.com.duke.protobuf.data.MapTeleportRequest mapTeleport = 9;</code>
   */
  @java.lang.Override
  public com.duke.protobuf.data.MapTeleportRequestOrBuilder getMapTeleportOrBuilder() {
    return getMapTeleport();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (userRegister_ != null) {
      output.writeMessage(1, getUserRegister());
    }
    if (userLogin_ != null) {
      output.writeMessage(2, getUserLogin());
    }
    if (createChar_ != null) {
      output.writeMessage(3, getCreateChar());
    }
    if (gameEnter_ != null) {
      output.writeMessage(4, getGameEnter());
    }
    if (gameLeave_ != null) {
      output.writeMessage(5, getGameLeave());
    }
    if (mapCharacterEnter_ != null) {
      output.writeMessage(6, getMapCharacterEnter());
    }
    if (mapEntitySync_ != null) {
      output.writeMessage(8, getMapEntitySync());
    }
    if (mapTeleport_ != null) {
      output.writeMessage(9, getMapTeleport());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (userRegister_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getUserRegister());
    }
    if (userLogin_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getUserLogin());
    }
    if (createChar_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getCreateChar());
    }
    if (gameEnter_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getGameEnter());
    }
    if (gameLeave_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getGameLeave());
    }
    if (mapCharacterEnter_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getMapCharacterEnter());
    }
    if (mapEntitySync_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getMapEntitySync());
    }
    if (mapTeleport_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, getMapTeleport());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.duke.protobuf.data.NetMessageRequest)) {
      return super.equals(obj);
    }
    com.duke.protobuf.data.NetMessageRequest other = (com.duke.protobuf.data.NetMessageRequest) obj;

    if (hasUserRegister() != other.hasUserRegister()) return false;
    if (hasUserRegister()) {
      if (!getUserRegister()
          .equals(other.getUserRegister())) return false;
    }
    if (hasUserLogin() != other.hasUserLogin()) return false;
    if (hasUserLogin()) {
      if (!getUserLogin()
          .equals(other.getUserLogin())) return false;
    }
    if (hasCreateChar() != other.hasCreateChar()) return false;
    if (hasCreateChar()) {
      if (!getCreateChar()
          .equals(other.getCreateChar())) return false;
    }
    if (hasGameEnter() != other.hasGameEnter()) return false;
    if (hasGameEnter()) {
      if (!getGameEnter()
          .equals(other.getGameEnter())) return false;
    }
    if (hasGameLeave() != other.hasGameLeave()) return false;
    if (hasGameLeave()) {
      if (!getGameLeave()
          .equals(other.getGameLeave())) return false;
    }
    if (hasMapCharacterEnter() != other.hasMapCharacterEnter()) return false;
    if (hasMapCharacterEnter()) {
      if (!getMapCharacterEnter()
          .equals(other.getMapCharacterEnter())) return false;
    }
    if (hasMapEntitySync() != other.hasMapEntitySync()) return false;
    if (hasMapEntitySync()) {
      if (!getMapEntitySync()
          .equals(other.getMapEntitySync())) return false;
    }
    if (hasMapTeleport() != other.hasMapTeleport()) return false;
    if (hasMapTeleport()) {
      if (!getMapTeleport()
          .equals(other.getMapTeleport())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasUserRegister()) {
      hash = (37 * hash) + USERREGISTER_FIELD_NUMBER;
      hash = (53 * hash) + getUserRegister().hashCode();
    }
    if (hasUserLogin()) {
      hash = (37 * hash) + USERLOGIN_FIELD_NUMBER;
      hash = (53 * hash) + getUserLogin().hashCode();
    }
    if (hasCreateChar()) {
      hash = (37 * hash) + CREATECHAR_FIELD_NUMBER;
      hash = (53 * hash) + getCreateChar().hashCode();
    }
    if (hasGameEnter()) {
      hash = (37 * hash) + GAMEENTER_FIELD_NUMBER;
      hash = (53 * hash) + getGameEnter().hashCode();
    }
    if (hasGameLeave()) {
      hash = (37 * hash) + GAMELEAVE_FIELD_NUMBER;
      hash = (53 * hash) + getGameLeave().hashCode();
    }
    if (hasMapCharacterEnter()) {
      hash = (37 * hash) + MAPCHARACTERENTER_FIELD_NUMBER;
      hash = (53 * hash) + getMapCharacterEnter().hashCode();
    }
    if (hasMapEntitySync()) {
      hash = (37 * hash) + MAPENTITYSYNC_FIELD_NUMBER;
      hash = (53 * hash) + getMapEntitySync().hashCode();
    }
    if (hasMapTeleport()) {
      hash = (37 * hash) + MAPTELEPORT_FIELD_NUMBER;
      hash = (53 * hash) + getMapTeleport().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.duke.protobuf.data.NetMessageRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.duke.protobuf.data.NetMessageRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.duke.protobuf.data.NetMessageRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.duke.protobuf.data.NetMessageRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.duke.protobuf.data.NetMessageRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.duke.protobuf.data.NetMessageRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.duke.protobuf.data.NetMessageRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.duke.protobuf.data.NetMessageRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.duke.protobuf.data.NetMessageRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.duke.protobuf.data.NetMessageRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.duke.protobuf.data.NetMessageRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.duke.protobuf.data.NetMessageRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.duke.protobuf.data.NetMessageRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.duke.protobuf.data.NetMessageRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.duke.protobuf.data.NetMessageRequest)
      com.duke.protobuf.data.NetMessageRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.duke.protobuf.data.Message.internal_static_com_duke_protobuf_data_NetMessageRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.duke.protobuf.data.Message.internal_static_com_duke_protobuf_data_NetMessageRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.duke.protobuf.data.NetMessageRequest.class, com.duke.protobuf.data.NetMessageRequest.Builder.class);
    }

    // Construct using com.duke.protobuf.data.NetMessageRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (userRegisterBuilder_ == null) {
        userRegister_ = null;
      } else {
        userRegister_ = null;
        userRegisterBuilder_ = null;
      }
      if (userLoginBuilder_ == null) {
        userLogin_ = null;
      } else {
        userLogin_ = null;
        userLoginBuilder_ = null;
      }
      if (createCharBuilder_ == null) {
        createChar_ = null;
      } else {
        createChar_ = null;
        createCharBuilder_ = null;
      }
      if (gameEnterBuilder_ == null) {
        gameEnter_ = null;
      } else {
        gameEnter_ = null;
        gameEnterBuilder_ = null;
      }
      if (gameLeaveBuilder_ == null) {
        gameLeave_ = null;
      } else {
        gameLeave_ = null;
        gameLeaveBuilder_ = null;
      }
      if (mapCharacterEnterBuilder_ == null) {
        mapCharacterEnter_ = null;
      } else {
        mapCharacterEnter_ = null;
        mapCharacterEnterBuilder_ = null;
      }
      if (mapEntitySyncBuilder_ == null) {
        mapEntitySync_ = null;
      } else {
        mapEntitySync_ = null;
        mapEntitySyncBuilder_ = null;
      }
      if (mapTeleportBuilder_ == null) {
        mapTeleport_ = null;
      } else {
        mapTeleport_ = null;
        mapTeleportBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.duke.protobuf.data.Message.internal_static_com_duke_protobuf_data_NetMessageRequest_descriptor;
    }

    @java.lang.Override
    public com.duke.protobuf.data.NetMessageRequest getDefaultInstanceForType() {
      return com.duke.protobuf.data.NetMessageRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.duke.protobuf.data.NetMessageRequest build() {
      com.duke.protobuf.data.NetMessageRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.duke.protobuf.data.NetMessageRequest buildPartial() {
      com.duke.protobuf.data.NetMessageRequest result = new com.duke.protobuf.data.NetMessageRequest(this);
      if (userRegisterBuilder_ == null) {
        result.userRegister_ = userRegister_;
      } else {
        result.userRegister_ = userRegisterBuilder_.build();
      }
      if (userLoginBuilder_ == null) {
        result.userLogin_ = userLogin_;
      } else {
        result.userLogin_ = userLoginBuilder_.build();
      }
      if (createCharBuilder_ == null) {
        result.createChar_ = createChar_;
      } else {
        result.createChar_ = createCharBuilder_.build();
      }
      if (gameEnterBuilder_ == null) {
        result.gameEnter_ = gameEnter_;
      } else {
        result.gameEnter_ = gameEnterBuilder_.build();
      }
      if (gameLeaveBuilder_ == null) {
        result.gameLeave_ = gameLeave_;
      } else {
        result.gameLeave_ = gameLeaveBuilder_.build();
      }
      if (mapCharacterEnterBuilder_ == null) {
        result.mapCharacterEnter_ = mapCharacterEnter_;
      } else {
        result.mapCharacterEnter_ = mapCharacterEnterBuilder_.build();
      }
      if (mapEntitySyncBuilder_ == null) {
        result.mapEntitySync_ = mapEntitySync_;
      } else {
        result.mapEntitySync_ = mapEntitySyncBuilder_.build();
      }
      if (mapTeleportBuilder_ == null) {
        result.mapTeleport_ = mapTeleport_;
      } else {
        result.mapTeleport_ = mapTeleportBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.duke.protobuf.data.NetMessageRequest) {
        return mergeFrom((com.duke.protobuf.data.NetMessageRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.duke.protobuf.data.NetMessageRequest other) {
      if (other == com.duke.protobuf.data.NetMessageRequest.getDefaultInstance()) return this;
      if (other.hasUserRegister()) {
        mergeUserRegister(other.getUserRegister());
      }
      if (other.hasUserLogin()) {
        mergeUserLogin(other.getUserLogin());
      }
      if (other.hasCreateChar()) {
        mergeCreateChar(other.getCreateChar());
      }
      if (other.hasGameEnter()) {
        mergeGameEnter(other.getGameEnter());
      }
      if (other.hasGameLeave()) {
        mergeGameLeave(other.getGameLeave());
      }
      if (other.hasMapCharacterEnter()) {
        mergeMapCharacterEnter(other.getMapCharacterEnter());
      }
      if (other.hasMapEntitySync()) {
        mergeMapEntitySync(other.getMapEntitySync());
      }
      if (other.hasMapTeleport()) {
        mergeMapTeleport(other.getMapTeleport());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.duke.protobuf.data.NetMessageRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.duke.protobuf.data.NetMessageRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.duke.protobuf.data.UserRegisterRequest userRegister_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.duke.protobuf.data.UserRegisterRequest, com.duke.protobuf.data.UserRegisterRequest.Builder, com.duke.protobuf.data.UserRegisterRequestOrBuilder> userRegisterBuilder_;
    /**
     * <code>.com.duke.protobuf.data.UserRegisterRequest userRegister = 1;</code>
     * @return Whether the userRegister field is set.
     */
    public boolean hasUserRegister() {
      return userRegisterBuilder_ != null || userRegister_ != null;
    }
    /**
     * <code>.com.duke.protobuf.data.UserRegisterRequest userRegister = 1;</code>
     * @return The userRegister.
     */
    public com.duke.protobuf.data.UserRegisterRequest getUserRegister() {
      if (userRegisterBuilder_ == null) {
        return userRegister_ == null ? com.duke.protobuf.data.UserRegisterRequest.getDefaultInstance() : userRegister_;
      } else {
        return userRegisterBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.duke.protobuf.data.UserRegisterRequest userRegister = 1;</code>
     */
    public Builder setUserRegister(com.duke.protobuf.data.UserRegisterRequest value) {
      if (userRegisterBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        userRegister_ = value;
        onChanged();
      } else {
        userRegisterBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.duke.protobuf.data.UserRegisterRequest userRegister = 1;</code>
     */
    public Builder setUserRegister(
        com.duke.protobuf.data.UserRegisterRequest.Builder builderForValue) {
      if (userRegisterBuilder_ == null) {
        userRegister_ = builderForValue.build();
        onChanged();
      } else {
        userRegisterBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.duke.protobuf.data.UserRegisterRequest userRegister = 1;</code>
     */
    public Builder mergeUserRegister(com.duke.protobuf.data.UserRegisterRequest value) {
      if (userRegisterBuilder_ == null) {
        if (userRegister_ != null) {
          userRegister_ =
            com.duke.protobuf.data.UserRegisterRequest.newBuilder(userRegister_).mergeFrom(value).buildPartial();
        } else {
          userRegister_ = value;
        }
        onChanged();
      } else {
        userRegisterBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.duke.protobuf.data.UserRegisterRequest userRegister = 1;</code>
     */
    public Builder clearUserRegister() {
      if (userRegisterBuilder_ == null) {
        userRegister_ = null;
        onChanged();
      } else {
        userRegister_ = null;
        userRegisterBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.duke.protobuf.data.UserRegisterRequest userRegister = 1;</code>
     */
    public com.duke.protobuf.data.UserRegisterRequest.Builder getUserRegisterBuilder() {
      
      onChanged();
      return getUserRegisterFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.duke.protobuf.data.UserRegisterRequest userRegister = 1;</code>
     */
    public com.duke.protobuf.data.UserRegisterRequestOrBuilder getUserRegisterOrBuilder() {
      if (userRegisterBuilder_ != null) {
        return userRegisterBuilder_.getMessageOrBuilder();
      } else {
        return userRegister_ == null ?
            com.duke.protobuf.data.UserRegisterRequest.getDefaultInstance() : userRegister_;
      }
    }
    /**
     * <code>.com.duke.protobuf.data.UserRegisterRequest userRegister = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.duke.protobuf.data.UserRegisterRequest, com.duke.protobuf.data.UserRegisterRequest.Builder, com.duke.protobuf.data.UserRegisterRequestOrBuilder> 
        getUserRegisterFieldBuilder() {
      if (userRegisterBuilder_ == null) {
        userRegisterBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.duke.protobuf.data.UserRegisterRequest, com.duke.protobuf.data.UserRegisterRequest.Builder, com.duke.protobuf.data.UserRegisterRequestOrBuilder>(
                getUserRegister(),
                getParentForChildren(),
                isClean());
        userRegister_ = null;
      }
      return userRegisterBuilder_;
    }

    private com.duke.protobuf.data.UserLoginRequest userLogin_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.duke.protobuf.data.UserLoginRequest, com.duke.protobuf.data.UserLoginRequest.Builder, com.duke.protobuf.data.UserLoginRequestOrBuilder> userLoginBuilder_;
    /**
     * <code>.com.duke.protobuf.data.UserLoginRequest userLogin = 2;</code>
     * @return Whether the userLogin field is set.
     */
    public boolean hasUserLogin() {
      return userLoginBuilder_ != null || userLogin_ != null;
    }
    /**
     * <code>.com.duke.protobuf.data.UserLoginRequest userLogin = 2;</code>
     * @return The userLogin.
     */
    public com.duke.protobuf.data.UserLoginRequest getUserLogin() {
      if (userLoginBuilder_ == null) {
        return userLogin_ == null ? com.duke.protobuf.data.UserLoginRequest.getDefaultInstance() : userLogin_;
      } else {
        return userLoginBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.duke.protobuf.data.UserLoginRequest userLogin = 2;</code>
     */
    public Builder setUserLogin(com.duke.protobuf.data.UserLoginRequest value) {
      if (userLoginBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        userLogin_ = value;
        onChanged();
      } else {
        userLoginBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.duke.protobuf.data.UserLoginRequest userLogin = 2;</code>
     */
    public Builder setUserLogin(
        com.duke.protobuf.data.UserLoginRequest.Builder builderForValue) {
      if (userLoginBuilder_ == null) {
        userLogin_ = builderForValue.build();
        onChanged();
      } else {
        userLoginBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.duke.protobuf.data.UserLoginRequest userLogin = 2;</code>
     */
    public Builder mergeUserLogin(com.duke.protobuf.data.UserLoginRequest value) {
      if (userLoginBuilder_ == null) {
        if (userLogin_ != null) {
          userLogin_ =
            com.duke.protobuf.data.UserLoginRequest.newBuilder(userLogin_).mergeFrom(value).buildPartial();
        } else {
          userLogin_ = value;
        }
        onChanged();
      } else {
        userLoginBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.duke.protobuf.data.UserLoginRequest userLogin = 2;</code>
     */
    public Builder clearUserLogin() {
      if (userLoginBuilder_ == null) {
        userLogin_ = null;
        onChanged();
      } else {
        userLogin_ = null;
        userLoginBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.duke.protobuf.data.UserLoginRequest userLogin = 2;</code>
     */
    public com.duke.protobuf.data.UserLoginRequest.Builder getUserLoginBuilder() {
      
      onChanged();
      return getUserLoginFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.duke.protobuf.data.UserLoginRequest userLogin = 2;</code>
     */
    public com.duke.protobuf.data.UserLoginRequestOrBuilder getUserLoginOrBuilder() {
      if (userLoginBuilder_ != null) {
        return userLoginBuilder_.getMessageOrBuilder();
      } else {
        return userLogin_ == null ?
            com.duke.protobuf.data.UserLoginRequest.getDefaultInstance() : userLogin_;
      }
    }
    /**
     * <code>.com.duke.protobuf.data.UserLoginRequest userLogin = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.duke.protobuf.data.UserLoginRequest, com.duke.protobuf.data.UserLoginRequest.Builder, com.duke.protobuf.data.UserLoginRequestOrBuilder> 
        getUserLoginFieldBuilder() {
      if (userLoginBuilder_ == null) {
        userLoginBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.duke.protobuf.data.UserLoginRequest, com.duke.protobuf.data.UserLoginRequest.Builder, com.duke.protobuf.data.UserLoginRequestOrBuilder>(
                getUserLogin(),
                getParentForChildren(),
                isClean());
        userLogin_ = null;
      }
      return userLoginBuilder_;
    }

    private com.duke.protobuf.data.UserCreateCharacterRequest createChar_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.duke.protobuf.data.UserCreateCharacterRequest, com.duke.protobuf.data.UserCreateCharacterRequest.Builder, com.duke.protobuf.data.UserCreateCharacterRequestOrBuilder> createCharBuilder_;
    /**
     * <code>.com.duke.protobuf.data.UserCreateCharacterRequest createChar = 3;</code>
     * @return Whether the createChar field is set.
     */
    public boolean hasCreateChar() {
      return createCharBuilder_ != null || createChar_ != null;
    }
    /**
     * <code>.com.duke.protobuf.data.UserCreateCharacterRequest createChar = 3;</code>
     * @return The createChar.
     */
    public com.duke.protobuf.data.UserCreateCharacterRequest getCreateChar() {
      if (createCharBuilder_ == null) {
        return createChar_ == null ? com.duke.protobuf.data.UserCreateCharacterRequest.getDefaultInstance() : createChar_;
      } else {
        return createCharBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.duke.protobuf.data.UserCreateCharacterRequest createChar = 3;</code>
     */
    public Builder setCreateChar(com.duke.protobuf.data.UserCreateCharacterRequest value) {
      if (createCharBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        createChar_ = value;
        onChanged();
      } else {
        createCharBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.duke.protobuf.data.UserCreateCharacterRequest createChar = 3;</code>
     */
    public Builder setCreateChar(
        com.duke.protobuf.data.UserCreateCharacterRequest.Builder builderForValue) {
      if (createCharBuilder_ == null) {
        createChar_ = builderForValue.build();
        onChanged();
      } else {
        createCharBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.duke.protobuf.data.UserCreateCharacterRequest createChar = 3;</code>
     */
    public Builder mergeCreateChar(com.duke.protobuf.data.UserCreateCharacterRequest value) {
      if (createCharBuilder_ == null) {
        if (createChar_ != null) {
          createChar_ =
            com.duke.protobuf.data.UserCreateCharacterRequest.newBuilder(createChar_).mergeFrom(value).buildPartial();
        } else {
          createChar_ = value;
        }
        onChanged();
      } else {
        createCharBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.duke.protobuf.data.UserCreateCharacterRequest createChar = 3;</code>
     */
    public Builder clearCreateChar() {
      if (createCharBuilder_ == null) {
        createChar_ = null;
        onChanged();
      } else {
        createChar_ = null;
        createCharBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.duke.protobuf.data.UserCreateCharacterRequest createChar = 3;</code>
     */
    public com.duke.protobuf.data.UserCreateCharacterRequest.Builder getCreateCharBuilder() {
      
      onChanged();
      return getCreateCharFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.duke.protobuf.data.UserCreateCharacterRequest createChar = 3;</code>
     */
    public com.duke.protobuf.data.UserCreateCharacterRequestOrBuilder getCreateCharOrBuilder() {
      if (createCharBuilder_ != null) {
        return createCharBuilder_.getMessageOrBuilder();
      } else {
        return createChar_ == null ?
            com.duke.protobuf.data.UserCreateCharacterRequest.getDefaultInstance() : createChar_;
      }
    }
    /**
     * <code>.com.duke.protobuf.data.UserCreateCharacterRequest createChar = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.duke.protobuf.data.UserCreateCharacterRequest, com.duke.protobuf.data.UserCreateCharacterRequest.Builder, com.duke.protobuf.data.UserCreateCharacterRequestOrBuilder> 
        getCreateCharFieldBuilder() {
      if (createCharBuilder_ == null) {
        createCharBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.duke.protobuf.data.UserCreateCharacterRequest, com.duke.protobuf.data.UserCreateCharacterRequest.Builder, com.duke.protobuf.data.UserCreateCharacterRequestOrBuilder>(
                getCreateChar(),
                getParentForChildren(),
                isClean());
        createChar_ = null;
      }
      return createCharBuilder_;
    }

    private com.duke.protobuf.data.UserGameEnterRequest gameEnter_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.duke.protobuf.data.UserGameEnterRequest, com.duke.protobuf.data.UserGameEnterRequest.Builder, com.duke.protobuf.data.UserGameEnterRequestOrBuilder> gameEnterBuilder_;
    /**
     * <code>.com.duke.protobuf.data.UserGameEnterRequest gameEnter = 4;</code>
     * @return Whether the gameEnter field is set.
     */
    public boolean hasGameEnter() {
      return gameEnterBuilder_ != null || gameEnter_ != null;
    }
    /**
     * <code>.com.duke.protobuf.data.UserGameEnterRequest gameEnter = 4;</code>
     * @return The gameEnter.
     */
    public com.duke.protobuf.data.UserGameEnterRequest getGameEnter() {
      if (gameEnterBuilder_ == null) {
        return gameEnter_ == null ? com.duke.protobuf.data.UserGameEnterRequest.getDefaultInstance() : gameEnter_;
      } else {
        return gameEnterBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.duke.protobuf.data.UserGameEnterRequest gameEnter = 4;</code>
     */
    public Builder setGameEnter(com.duke.protobuf.data.UserGameEnterRequest value) {
      if (gameEnterBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        gameEnter_ = value;
        onChanged();
      } else {
        gameEnterBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.duke.protobuf.data.UserGameEnterRequest gameEnter = 4;</code>
     */
    public Builder setGameEnter(
        com.duke.protobuf.data.UserGameEnterRequest.Builder builderForValue) {
      if (gameEnterBuilder_ == null) {
        gameEnter_ = builderForValue.build();
        onChanged();
      } else {
        gameEnterBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.duke.protobuf.data.UserGameEnterRequest gameEnter = 4;</code>
     */
    public Builder mergeGameEnter(com.duke.protobuf.data.UserGameEnterRequest value) {
      if (gameEnterBuilder_ == null) {
        if (gameEnter_ != null) {
          gameEnter_ =
            com.duke.protobuf.data.UserGameEnterRequest.newBuilder(gameEnter_).mergeFrom(value).buildPartial();
        } else {
          gameEnter_ = value;
        }
        onChanged();
      } else {
        gameEnterBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.duke.protobuf.data.UserGameEnterRequest gameEnter = 4;</code>
     */
    public Builder clearGameEnter() {
      if (gameEnterBuilder_ == null) {
        gameEnter_ = null;
        onChanged();
      } else {
        gameEnter_ = null;
        gameEnterBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.duke.protobuf.data.UserGameEnterRequest gameEnter = 4;</code>
     */
    public com.duke.protobuf.data.UserGameEnterRequest.Builder getGameEnterBuilder() {
      
      onChanged();
      return getGameEnterFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.duke.protobuf.data.UserGameEnterRequest gameEnter = 4;</code>
     */
    public com.duke.protobuf.data.UserGameEnterRequestOrBuilder getGameEnterOrBuilder() {
      if (gameEnterBuilder_ != null) {
        return gameEnterBuilder_.getMessageOrBuilder();
      } else {
        return gameEnter_ == null ?
            com.duke.protobuf.data.UserGameEnterRequest.getDefaultInstance() : gameEnter_;
      }
    }
    /**
     * <code>.com.duke.protobuf.data.UserGameEnterRequest gameEnter = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.duke.protobuf.data.UserGameEnterRequest, com.duke.protobuf.data.UserGameEnterRequest.Builder, com.duke.protobuf.data.UserGameEnterRequestOrBuilder> 
        getGameEnterFieldBuilder() {
      if (gameEnterBuilder_ == null) {
        gameEnterBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.duke.protobuf.data.UserGameEnterRequest, com.duke.protobuf.data.UserGameEnterRequest.Builder, com.duke.protobuf.data.UserGameEnterRequestOrBuilder>(
                getGameEnter(),
                getParentForChildren(),
                isClean());
        gameEnter_ = null;
      }
      return gameEnterBuilder_;
    }

    private com.duke.protobuf.data.UserGameLeaveRequest gameLeave_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.duke.protobuf.data.UserGameLeaveRequest, com.duke.protobuf.data.UserGameLeaveRequest.Builder, com.duke.protobuf.data.UserGameLeaveRequestOrBuilder> gameLeaveBuilder_;
    /**
     * <code>.com.duke.protobuf.data.UserGameLeaveRequest gameLeave = 5;</code>
     * @return Whether the gameLeave field is set.
     */
    public boolean hasGameLeave() {
      return gameLeaveBuilder_ != null || gameLeave_ != null;
    }
    /**
     * <code>.com.duke.protobuf.data.UserGameLeaveRequest gameLeave = 5;</code>
     * @return The gameLeave.
     */
    public com.duke.protobuf.data.UserGameLeaveRequest getGameLeave() {
      if (gameLeaveBuilder_ == null) {
        return gameLeave_ == null ? com.duke.protobuf.data.UserGameLeaveRequest.getDefaultInstance() : gameLeave_;
      } else {
        return gameLeaveBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.duke.protobuf.data.UserGameLeaveRequest gameLeave = 5;</code>
     */
    public Builder setGameLeave(com.duke.protobuf.data.UserGameLeaveRequest value) {
      if (gameLeaveBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        gameLeave_ = value;
        onChanged();
      } else {
        gameLeaveBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.duke.protobuf.data.UserGameLeaveRequest gameLeave = 5;</code>
     */
    public Builder setGameLeave(
        com.duke.protobuf.data.UserGameLeaveRequest.Builder builderForValue) {
      if (gameLeaveBuilder_ == null) {
        gameLeave_ = builderForValue.build();
        onChanged();
      } else {
        gameLeaveBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.duke.protobuf.data.UserGameLeaveRequest gameLeave = 5;</code>
     */
    public Builder mergeGameLeave(com.duke.protobuf.data.UserGameLeaveRequest value) {
      if (gameLeaveBuilder_ == null) {
        if (gameLeave_ != null) {
          gameLeave_ =
            com.duke.protobuf.data.UserGameLeaveRequest.newBuilder(gameLeave_).mergeFrom(value).buildPartial();
        } else {
          gameLeave_ = value;
        }
        onChanged();
      } else {
        gameLeaveBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.duke.protobuf.data.UserGameLeaveRequest gameLeave = 5;</code>
     */
    public Builder clearGameLeave() {
      if (gameLeaveBuilder_ == null) {
        gameLeave_ = null;
        onChanged();
      } else {
        gameLeave_ = null;
        gameLeaveBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.duke.protobuf.data.UserGameLeaveRequest gameLeave = 5;</code>
     */
    public com.duke.protobuf.data.UserGameLeaveRequest.Builder getGameLeaveBuilder() {
      
      onChanged();
      return getGameLeaveFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.duke.protobuf.data.UserGameLeaveRequest gameLeave = 5;</code>
     */
    public com.duke.protobuf.data.UserGameLeaveRequestOrBuilder getGameLeaveOrBuilder() {
      if (gameLeaveBuilder_ != null) {
        return gameLeaveBuilder_.getMessageOrBuilder();
      } else {
        return gameLeave_ == null ?
            com.duke.protobuf.data.UserGameLeaveRequest.getDefaultInstance() : gameLeave_;
      }
    }
    /**
     * <code>.com.duke.protobuf.data.UserGameLeaveRequest gameLeave = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.duke.protobuf.data.UserGameLeaveRequest, com.duke.protobuf.data.UserGameLeaveRequest.Builder, com.duke.protobuf.data.UserGameLeaveRequestOrBuilder> 
        getGameLeaveFieldBuilder() {
      if (gameLeaveBuilder_ == null) {
        gameLeaveBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.duke.protobuf.data.UserGameLeaveRequest, com.duke.protobuf.data.UserGameLeaveRequest.Builder, com.duke.protobuf.data.UserGameLeaveRequestOrBuilder>(
                getGameLeave(),
                getParentForChildren(),
                isClean());
        gameLeave_ = null;
      }
      return gameLeaveBuilder_;
    }

    private com.duke.protobuf.data.MapCharacterEnterRequest mapCharacterEnter_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.duke.protobuf.data.MapCharacterEnterRequest, com.duke.protobuf.data.MapCharacterEnterRequest.Builder, com.duke.protobuf.data.MapCharacterEnterRequestOrBuilder> mapCharacterEnterBuilder_;
    /**
     * <code>.com.duke.protobuf.data.MapCharacterEnterRequest mapCharacterEnter = 6;</code>
     * @return Whether the mapCharacterEnter field is set.
     */
    public boolean hasMapCharacterEnter() {
      return mapCharacterEnterBuilder_ != null || mapCharacterEnter_ != null;
    }
    /**
     * <code>.com.duke.protobuf.data.MapCharacterEnterRequest mapCharacterEnter = 6;</code>
     * @return The mapCharacterEnter.
     */
    public com.duke.protobuf.data.MapCharacterEnterRequest getMapCharacterEnter() {
      if (mapCharacterEnterBuilder_ == null) {
        return mapCharacterEnter_ == null ? com.duke.protobuf.data.MapCharacterEnterRequest.getDefaultInstance() : mapCharacterEnter_;
      } else {
        return mapCharacterEnterBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.duke.protobuf.data.MapCharacterEnterRequest mapCharacterEnter = 6;</code>
     */
    public Builder setMapCharacterEnter(com.duke.protobuf.data.MapCharacterEnterRequest value) {
      if (mapCharacterEnterBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        mapCharacterEnter_ = value;
        onChanged();
      } else {
        mapCharacterEnterBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.duke.protobuf.data.MapCharacterEnterRequest mapCharacterEnter = 6;</code>
     */
    public Builder setMapCharacterEnter(
        com.duke.protobuf.data.MapCharacterEnterRequest.Builder builderForValue) {
      if (mapCharacterEnterBuilder_ == null) {
        mapCharacterEnter_ = builderForValue.build();
        onChanged();
      } else {
        mapCharacterEnterBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.duke.protobuf.data.MapCharacterEnterRequest mapCharacterEnter = 6;</code>
     */
    public Builder mergeMapCharacterEnter(com.duke.protobuf.data.MapCharacterEnterRequest value) {
      if (mapCharacterEnterBuilder_ == null) {
        if (mapCharacterEnter_ != null) {
          mapCharacterEnter_ =
            com.duke.protobuf.data.MapCharacterEnterRequest.newBuilder(mapCharacterEnter_).mergeFrom(value).buildPartial();
        } else {
          mapCharacterEnter_ = value;
        }
        onChanged();
      } else {
        mapCharacterEnterBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.duke.protobuf.data.MapCharacterEnterRequest mapCharacterEnter = 6;</code>
     */
    public Builder clearMapCharacterEnter() {
      if (mapCharacterEnterBuilder_ == null) {
        mapCharacterEnter_ = null;
        onChanged();
      } else {
        mapCharacterEnter_ = null;
        mapCharacterEnterBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.duke.protobuf.data.MapCharacterEnterRequest mapCharacterEnter = 6;</code>
     */
    public com.duke.protobuf.data.MapCharacterEnterRequest.Builder getMapCharacterEnterBuilder() {
      
      onChanged();
      return getMapCharacterEnterFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.duke.protobuf.data.MapCharacterEnterRequest mapCharacterEnter = 6;</code>
     */
    public com.duke.protobuf.data.MapCharacterEnterRequestOrBuilder getMapCharacterEnterOrBuilder() {
      if (mapCharacterEnterBuilder_ != null) {
        return mapCharacterEnterBuilder_.getMessageOrBuilder();
      } else {
        return mapCharacterEnter_ == null ?
            com.duke.protobuf.data.MapCharacterEnterRequest.getDefaultInstance() : mapCharacterEnter_;
      }
    }
    /**
     * <code>.com.duke.protobuf.data.MapCharacterEnterRequest mapCharacterEnter = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.duke.protobuf.data.MapCharacterEnterRequest, com.duke.protobuf.data.MapCharacterEnterRequest.Builder, com.duke.protobuf.data.MapCharacterEnterRequestOrBuilder> 
        getMapCharacterEnterFieldBuilder() {
      if (mapCharacterEnterBuilder_ == null) {
        mapCharacterEnterBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.duke.protobuf.data.MapCharacterEnterRequest, com.duke.protobuf.data.MapCharacterEnterRequest.Builder, com.duke.protobuf.data.MapCharacterEnterRequestOrBuilder>(
                getMapCharacterEnter(),
                getParentForChildren(),
                isClean());
        mapCharacterEnter_ = null;
      }
      return mapCharacterEnterBuilder_;
    }

    private com.duke.protobuf.data.MapEntitySyncRequest mapEntitySync_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.duke.protobuf.data.MapEntitySyncRequest, com.duke.protobuf.data.MapEntitySyncRequest.Builder, com.duke.protobuf.data.MapEntitySyncRequestOrBuilder> mapEntitySyncBuilder_;
    /**
     * <code>.com.duke.protobuf.data.MapEntitySyncRequest mapEntitySync = 8;</code>
     * @return Whether the mapEntitySync field is set.
     */
    public boolean hasMapEntitySync() {
      return mapEntitySyncBuilder_ != null || mapEntitySync_ != null;
    }
    /**
     * <code>.com.duke.protobuf.data.MapEntitySyncRequest mapEntitySync = 8;</code>
     * @return The mapEntitySync.
     */
    public com.duke.protobuf.data.MapEntitySyncRequest getMapEntitySync() {
      if (mapEntitySyncBuilder_ == null) {
        return mapEntitySync_ == null ? com.duke.protobuf.data.MapEntitySyncRequest.getDefaultInstance() : mapEntitySync_;
      } else {
        return mapEntitySyncBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.duke.protobuf.data.MapEntitySyncRequest mapEntitySync = 8;</code>
     */
    public Builder setMapEntitySync(com.duke.protobuf.data.MapEntitySyncRequest value) {
      if (mapEntitySyncBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        mapEntitySync_ = value;
        onChanged();
      } else {
        mapEntitySyncBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.duke.protobuf.data.MapEntitySyncRequest mapEntitySync = 8;</code>
     */
    public Builder setMapEntitySync(
        com.duke.protobuf.data.MapEntitySyncRequest.Builder builderForValue) {
      if (mapEntitySyncBuilder_ == null) {
        mapEntitySync_ = builderForValue.build();
        onChanged();
      } else {
        mapEntitySyncBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.duke.protobuf.data.MapEntitySyncRequest mapEntitySync = 8;</code>
     */
    public Builder mergeMapEntitySync(com.duke.protobuf.data.MapEntitySyncRequest value) {
      if (mapEntitySyncBuilder_ == null) {
        if (mapEntitySync_ != null) {
          mapEntitySync_ =
            com.duke.protobuf.data.MapEntitySyncRequest.newBuilder(mapEntitySync_).mergeFrom(value).buildPartial();
        } else {
          mapEntitySync_ = value;
        }
        onChanged();
      } else {
        mapEntitySyncBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.duke.protobuf.data.MapEntitySyncRequest mapEntitySync = 8;</code>
     */
    public Builder clearMapEntitySync() {
      if (mapEntitySyncBuilder_ == null) {
        mapEntitySync_ = null;
        onChanged();
      } else {
        mapEntitySync_ = null;
        mapEntitySyncBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.duke.protobuf.data.MapEntitySyncRequest mapEntitySync = 8;</code>
     */
    public com.duke.protobuf.data.MapEntitySyncRequest.Builder getMapEntitySyncBuilder() {
      
      onChanged();
      return getMapEntitySyncFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.duke.protobuf.data.MapEntitySyncRequest mapEntitySync = 8;</code>
     */
    public com.duke.protobuf.data.MapEntitySyncRequestOrBuilder getMapEntitySyncOrBuilder() {
      if (mapEntitySyncBuilder_ != null) {
        return mapEntitySyncBuilder_.getMessageOrBuilder();
      } else {
        return mapEntitySync_ == null ?
            com.duke.protobuf.data.MapEntitySyncRequest.getDefaultInstance() : mapEntitySync_;
      }
    }
    /**
     * <code>.com.duke.protobuf.data.MapEntitySyncRequest mapEntitySync = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.duke.protobuf.data.MapEntitySyncRequest, com.duke.protobuf.data.MapEntitySyncRequest.Builder, com.duke.protobuf.data.MapEntitySyncRequestOrBuilder> 
        getMapEntitySyncFieldBuilder() {
      if (mapEntitySyncBuilder_ == null) {
        mapEntitySyncBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.duke.protobuf.data.MapEntitySyncRequest, com.duke.protobuf.data.MapEntitySyncRequest.Builder, com.duke.protobuf.data.MapEntitySyncRequestOrBuilder>(
                getMapEntitySync(),
                getParentForChildren(),
                isClean());
        mapEntitySync_ = null;
      }
      return mapEntitySyncBuilder_;
    }

    private com.duke.protobuf.data.MapTeleportRequest mapTeleport_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.duke.protobuf.data.MapTeleportRequest, com.duke.protobuf.data.MapTeleportRequest.Builder, com.duke.protobuf.data.MapTeleportRequestOrBuilder> mapTeleportBuilder_;
    /**
     * <code>.com.duke.protobuf.data.MapTeleportRequest mapTeleport = 9;</code>
     * @return Whether the mapTeleport field is set.
     */
    public boolean hasMapTeleport() {
      return mapTeleportBuilder_ != null || mapTeleport_ != null;
    }
    /**
     * <code>.com.duke.protobuf.data.MapTeleportRequest mapTeleport = 9;</code>
     * @return The mapTeleport.
     */
    public com.duke.protobuf.data.MapTeleportRequest getMapTeleport() {
      if (mapTeleportBuilder_ == null) {
        return mapTeleport_ == null ? com.duke.protobuf.data.MapTeleportRequest.getDefaultInstance() : mapTeleport_;
      } else {
        return mapTeleportBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.duke.protobuf.data.MapTeleportRequest mapTeleport = 9;</code>
     */
    public Builder setMapTeleport(com.duke.protobuf.data.MapTeleportRequest value) {
      if (mapTeleportBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        mapTeleport_ = value;
        onChanged();
      } else {
        mapTeleportBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.duke.protobuf.data.MapTeleportRequest mapTeleport = 9;</code>
     */
    public Builder setMapTeleport(
        com.duke.protobuf.data.MapTeleportRequest.Builder builderForValue) {
      if (mapTeleportBuilder_ == null) {
        mapTeleport_ = builderForValue.build();
        onChanged();
      } else {
        mapTeleportBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.duke.protobuf.data.MapTeleportRequest mapTeleport = 9;</code>
     */
    public Builder mergeMapTeleport(com.duke.protobuf.data.MapTeleportRequest value) {
      if (mapTeleportBuilder_ == null) {
        if (mapTeleport_ != null) {
          mapTeleport_ =
            com.duke.protobuf.data.MapTeleportRequest.newBuilder(mapTeleport_).mergeFrom(value).buildPartial();
        } else {
          mapTeleport_ = value;
        }
        onChanged();
      } else {
        mapTeleportBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.duke.protobuf.data.MapTeleportRequest mapTeleport = 9;</code>
     */
    public Builder clearMapTeleport() {
      if (mapTeleportBuilder_ == null) {
        mapTeleport_ = null;
        onChanged();
      } else {
        mapTeleport_ = null;
        mapTeleportBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.duke.protobuf.data.MapTeleportRequest mapTeleport = 9;</code>
     */
    public com.duke.protobuf.data.MapTeleportRequest.Builder getMapTeleportBuilder() {
      
      onChanged();
      return getMapTeleportFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.duke.protobuf.data.MapTeleportRequest mapTeleport = 9;</code>
     */
    public com.duke.protobuf.data.MapTeleportRequestOrBuilder getMapTeleportOrBuilder() {
      if (mapTeleportBuilder_ != null) {
        return mapTeleportBuilder_.getMessageOrBuilder();
      } else {
        return mapTeleport_ == null ?
            com.duke.protobuf.data.MapTeleportRequest.getDefaultInstance() : mapTeleport_;
      }
    }
    /**
     * <code>.com.duke.protobuf.data.MapTeleportRequest mapTeleport = 9;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.duke.protobuf.data.MapTeleportRequest, com.duke.protobuf.data.MapTeleportRequest.Builder, com.duke.protobuf.data.MapTeleportRequestOrBuilder> 
        getMapTeleportFieldBuilder() {
      if (mapTeleportBuilder_ == null) {
        mapTeleportBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.duke.protobuf.data.MapTeleportRequest, com.duke.protobuf.data.MapTeleportRequest.Builder, com.duke.protobuf.data.MapTeleportRequestOrBuilder>(
                getMapTeleport(),
                getParentForChildren(),
                isClean());
        mapTeleport_ = null;
      }
      return mapTeleportBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.duke.protobuf.data.NetMessageRequest)
  }

  // @@protoc_insertion_point(class_scope:com.duke.protobuf.data.NetMessageRequest)
  private static final com.duke.protobuf.data.NetMessageRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.duke.protobuf.data.NetMessageRequest();
  }

  public static com.duke.protobuf.data.NetMessageRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NetMessageRequest>
      PARSER = new com.google.protobuf.AbstractParser<NetMessageRequest>() {
    @java.lang.Override
    public NetMessageRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new NetMessageRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<NetMessageRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<NetMessageRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.duke.protobuf.data.NetMessageRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

