// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/message.proto

package com.duke.protobuf.data;

public interface NetMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.duke.protobuf.data.NetMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.duke.protobuf.data.NetMessageRequest Request = 1;</code>
   * @return Whether the request field is set.
   */
  boolean hasRequest();
  /**
   * <code>.com.duke.protobuf.data.NetMessageRequest Request = 1;</code>
   * @return The request.
   */
  com.duke.protobuf.data.NetMessageRequest getRequest();
  /**
   * <code>.com.duke.protobuf.data.NetMessageRequest Request = 1;</code>
   */
  com.duke.protobuf.data.NetMessageRequestOrBuilder getRequestOrBuilder();

  /**
   * <code>.com.duke.protobuf.data.NetMessageResponse Response = 2;</code>
   * @return Whether the response field is set.
   */
  boolean hasResponse();
  /**
   * <code>.com.duke.protobuf.data.NetMessageResponse Response = 2;</code>
   * @return The response.
   */
  com.duke.protobuf.data.NetMessageResponse getResponse();
  /**
   * <code>.com.duke.protobuf.data.NetMessageResponse Response = 2;</code>
   */
  com.duke.protobuf.data.NetMessageResponseOrBuilder getResponseOrBuilder();
}
