// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.duke.protobuf.data;

public interface NFriendInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.duke.protobuf.data.NFriendInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>.com.duke.protobuf.data.NCharacterInfo friendInfo = 2;</code>
   * @return Whether the friendInfo field is set.
   */
  boolean hasFriendInfo();
  /**
   * <code>.com.duke.protobuf.data.NCharacterInfo friendInfo = 2;</code>
   * @return The friendInfo.
   */
  com.duke.protobuf.data.NCharacterInfo getFriendInfo();
  /**
   * <code>.com.duke.protobuf.data.NCharacterInfo friendInfo = 2;</code>
   */
  com.duke.protobuf.data.NCharacterInfoOrBuilder getFriendInfoOrBuilder();

  /**
   * <code>int32 status = 3;</code>
   * @return The status.
   */
  int getStatus();
}
