// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.duke.protobuf.data;

public interface StatusNotifyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.duke.protobuf.data.StatusNotify)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.duke.protobuf.data.NStatus status = 1;</code>
   */
  java.util.List<com.duke.protobuf.data.NStatus> 
      getStatusList();
  /**
   * <code>repeated .com.duke.protobuf.data.NStatus status = 1;</code>
   */
  com.duke.protobuf.data.NStatus getStatus(int index);
  /**
   * <code>repeated .com.duke.protobuf.data.NStatus status = 1;</code>
   */
  int getStatusCount();
  /**
   * <code>repeated .com.duke.protobuf.data.NStatus status = 1;</code>
   */
  java.util.List<? extends com.duke.protobuf.data.NStatusOrBuilder> 
      getStatusOrBuilderList();
  /**
   * <code>repeated .com.duke.protobuf.data.NStatus status = 1;</code>
   */
  com.duke.protobuf.data.NStatusOrBuilder getStatusOrBuilder(
      int index);
}
