// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.duke.protobuf.data;

public interface TeamLeaveRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.duke.protobuf.data.TeamLeaveRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 teamId = 1;</code>
   * @return The teamId.
   */
  int getTeamId();

  /**
   * <code>int32 characterId = 2;</code>
   * @return The characterId.
   */
  int getCharacterId();
}
