// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.duke.protobuf.data;

public interface UserGameEnterResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.duke.protobuf.data.UserGameEnterResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.duke.protobuf.data.RESULT result = 1;</code>
   * @return The enum numeric value on the wire for result.
   */
  int getResultValue();
  /**
   * <code>.com.duke.protobuf.data.RESULT result = 1;</code>
   * @return The result.
   */
  com.duke.protobuf.data.RESULT getResult();

  /**
   * <code>string errormsg = 2;</code>
   * @return The errormsg.
   */
  java.lang.String getErrormsg();
  /**
   * <code>string errormsg = 2;</code>
   * @return The bytes for errormsg.
   */
  com.google.protobuf.ByteString
      getErrormsgBytes();

  /**
   * <code>.com.duke.protobuf.data.NCharacterInfo character = 3;</code>
   * @return Whether the character field is set.
   */
  boolean hasCharacter();
  /**
   * <code>.com.duke.protobuf.data.NCharacterInfo character = 3;</code>
   * @return The character.
   */
  com.duke.protobuf.data.NCharacterInfo getCharacter();
  /**
   * <code>.com.duke.protobuf.data.NCharacterInfo character = 3;</code>
   */
  com.duke.protobuf.data.NCharacterInfoOrBuilder getCharacterOrBuilder();
}
