// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/message.proto

package com.duke.protobuf.data;

/**
 * Protobuf type {@code com.duke.protobuf.data.UserCreateCharacterResponse}
 */
public final class UserCreateCharacterResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.duke.protobuf.data.UserCreateCharacterResponse)
    UserCreateCharacterResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UserCreateCharacterResponse.newBuilder() to construct.
  private UserCreateCharacterResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UserCreateCharacterResponse() {
    result_ = 0;
    errormsg_ = "";
    characters_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new UserCreateCharacterResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UserCreateCharacterResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            result_ = rawValue;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            errormsg_ = s;
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              characters_ = new java.util.ArrayList<com.duke.protobuf.data.NCharacterInfo>();
              mutable_bitField0_ |= 0x00000001;
            }
            characters_.add(
                input.readMessage(com.duke.protobuf.data.NCharacterInfo.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        characters_ = java.util.Collections.unmodifiableList(characters_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.duke.protobuf.data.Message.internal_static_com_duke_protobuf_data_UserCreateCharacterResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.duke.protobuf.data.Message.internal_static_com_duke_protobuf_data_UserCreateCharacterResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.duke.protobuf.data.UserCreateCharacterResponse.class, com.duke.protobuf.data.UserCreateCharacterResponse.Builder.class);
  }

  public static final int RESULT_FIELD_NUMBER = 1;
  private int result_;
  /**
   * <code>.com.duke.protobuf.data.RESULT result = 1;</code>
   * @return The enum numeric value on the wire for result.
   */
  @java.lang.Override public int getResultValue() {
    return result_;
  }
  /**
   * <code>.com.duke.protobuf.data.RESULT result = 1;</code>
   * @return The result.
   */
  @java.lang.Override public com.duke.protobuf.data.RESULT getResult() {
    @SuppressWarnings("deprecation")
    com.duke.protobuf.data.RESULT result = com.duke.protobuf.data.RESULT.valueOf(result_);
    return result == null ? com.duke.protobuf.data.RESULT.UNRECOGNIZED : result;
  }

  public static final int ERRORMSG_FIELD_NUMBER = 2;
  private volatile java.lang.Object errormsg_;
  /**
   * <code>string errormsg = 2;</code>
   * @return The errormsg.
   */
  @java.lang.Override
  public java.lang.String getErrormsg() {
    java.lang.Object ref = errormsg_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      errormsg_ = s;
      return s;
    }
  }
  /**
   * <code>string errormsg = 2;</code>
   * @return The bytes for errormsg.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getErrormsgBytes() {
    java.lang.Object ref = errormsg_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      errormsg_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CHARACTERS_FIELD_NUMBER = 3;
  private java.util.List<com.duke.protobuf.data.NCharacterInfo> characters_;
  /**
   * <code>repeated .com.duke.protobuf.data.NCharacterInfo characters = 3;</code>
   */
  @java.lang.Override
  public java.util.List<com.duke.protobuf.data.NCharacterInfo> getCharactersList() {
    return characters_;
  }
  /**
   * <code>repeated .com.duke.protobuf.data.NCharacterInfo characters = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.duke.protobuf.data.NCharacterInfoOrBuilder> 
      getCharactersOrBuilderList() {
    return characters_;
  }
  /**
   * <code>repeated .com.duke.protobuf.data.NCharacterInfo characters = 3;</code>
   */
  @java.lang.Override
  public int getCharactersCount() {
    return characters_.size();
  }
  /**
   * <code>repeated .com.duke.protobuf.data.NCharacterInfo characters = 3;</code>
   */
  @java.lang.Override
  public com.duke.protobuf.data.NCharacterInfo getCharacters(int index) {
    return characters_.get(index);
  }
  /**
   * <code>repeated .com.duke.protobuf.data.NCharacterInfo characters = 3;</code>
   */
  @java.lang.Override
  public com.duke.protobuf.data.NCharacterInfoOrBuilder getCharactersOrBuilder(
      int index) {
    return characters_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (result_ != com.duke.protobuf.data.RESULT.SUCCESS.getNumber()) {
      output.writeEnum(1, result_);
    }
    if (!getErrormsgBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, errormsg_);
    }
    for (int i = 0; i < characters_.size(); i++) {
      output.writeMessage(3, characters_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (result_ != com.duke.protobuf.data.RESULT.SUCCESS.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, result_);
    }
    if (!getErrormsgBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, errormsg_);
    }
    for (int i = 0; i < characters_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, characters_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.duke.protobuf.data.UserCreateCharacterResponse)) {
      return super.equals(obj);
    }
    com.duke.protobuf.data.UserCreateCharacterResponse other = (com.duke.protobuf.data.UserCreateCharacterResponse) obj;

    if (result_ != other.result_) return false;
    if (!getErrormsg()
        .equals(other.getErrormsg())) return false;
    if (!getCharactersList()
        .equals(other.getCharactersList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RESULT_FIELD_NUMBER;
    hash = (53 * hash) + result_;
    hash = (37 * hash) + ERRORMSG_FIELD_NUMBER;
    hash = (53 * hash) + getErrormsg().hashCode();
    if (getCharactersCount() > 0) {
      hash = (37 * hash) + CHARACTERS_FIELD_NUMBER;
      hash = (53 * hash) + getCharactersList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.duke.protobuf.data.UserCreateCharacterResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.duke.protobuf.data.UserCreateCharacterResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.duke.protobuf.data.UserCreateCharacterResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.duke.protobuf.data.UserCreateCharacterResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.duke.protobuf.data.UserCreateCharacterResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.duke.protobuf.data.UserCreateCharacterResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.duke.protobuf.data.UserCreateCharacterResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.duke.protobuf.data.UserCreateCharacterResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.duke.protobuf.data.UserCreateCharacterResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.duke.protobuf.data.UserCreateCharacterResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.duke.protobuf.data.UserCreateCharacterResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.duke.protobuf.data.UserCreateCharacterResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.duke.protobuf.data.UserCreateCharacterResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.duke.protobuf.data.UserCreateCharacterResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.duke.protobuf.data.UserCreateCharacterResponse)
      com.duke.protobuf.data.UserCreateCharacterResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.duke.protobuf.data.Message.internal_static_com_duke_protobuf_data_UserCreateCharacterResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.duke.protobuf.data.Message.internal_static_com_duke_protobuf_data_UserCreateCharacterResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.duke.protobuf.data.UserCreateCharacterResponse.class, com.duke.protobuf.data.UserCreateCharacterResponse.Builder.class);
    }

    // Construct using com.duke.protobuf.data.UserCreateCharacterResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getCharactersFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      result_ = 0;

      errormsg_ = "";

      if (charactersBuilder_ == null) {
        characters_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        charactersBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.duke.protobuf.data.Message.internal_static_com_duke_protobuf_data_UserCreateCharacterResponse_descriptor;
    }

    @java.lang.Override
    public com.duke.protobuf.data.UserCreateCharacterResponse getDefaultInstanceForType() {
      return com.duke.protobuf.data.UserCreateCharacterResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.duke.protobuf.data.UserCreateCharacterResponse build() {
      com.duke.protobuf.data.UserCreateCharacterResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.duke.protobuf.data.UserCreateCharacterResponse buildPartial() {
      com.duke.protobuf.data.UserCreateCharacterResponse result = new com.duke.protobuf.data.UserCreateCharacterResponse(this);
      int from_bitField0_ = bitField0_;
      result.result_ = result_;
      result.errormsg_ = errormsg_;
      if (charactersBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          characters_ = java.util.Collections.unmodifiableList(characters_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.characters_ = characters_;
      } else {
        result.characters_ = charactersBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.duke.protobuf.data.UserCreateCharacterResponse) {
        return mergeFrom((com.duke.protobuf.data.UserCreateCharacterResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.duke.protobuf.data.UserCreateCharacterResponse other) {
      if (other == com.duke.protobuf.data.UserCreateCharacterResponse.getDefaultInstance()) return this;
      if (other.result_ != 0) {
        setResultValue(other.getResultValue());
      }
      if (!other.getErrormsg().isEmpty()) {
        errormsg_ = other.errormsg_;
        onChanged();
      }
      if (charactersBuilder_ == null) {
        if (!other.characters_.isEmpty()) {
          if (characters_.isEmpty()) {
            characters_ = other.characters_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureCharactersIsMutable();
            characters_.addAll(other.characters_);
          }
          onChanged();
        }
      } else {
        if (!other.characters_.isEmpty()) {
          if (charactersBuilder_.isEmpty()) {
            charactersBuilder_.dispose();
            charactersBuilder_ = null;
            characters_ = other.characters_;
            bitField0_ = (bitField0_ & ~0x00000001);
            charactersBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getCharactersFieldBuilder() : null;
          } else {
            charactersBuilder_.addAllMessages(other.characters_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.duke.protobuf.data.UserCreateCharacterResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.duke.protobuf.data.UserCreateCharacterResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int result_ = 0;
    /**
     * <code>.com.duke.protobuf.data.RESULT result = 1;</code>
     * @return The enum numeric value on the wire for result.
     */
    @java.lang.Override public int getResultValue() {
      return result_;
    }
    /**
     * <code>.com.duke.protobuf.data.RESULT result = 1;</code>
     * @param value The enum numeric value on the wire for result to set.
     * @return This builder for chaining.
     */
    public Builder setResultValue(int value) {
      
      result_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.com.duke.protobuf.data.RESULT result = 1;</code>
     * @return The result.
     */
    @java.lang.Override
    public com.duke.protobuf.data.RESULT getResult() {
      @SuppressWarnings("deprecation")
      com.duke.protobuf.data.RESULT result = com.duke.protobuf.data.RESULT.valueOf(result_);
      return result == null ? com.duke.protobuf.data.RESULT.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.duke.protobuf.data.RESULT result = 1;</code>
     * @param value The result to set.
     * @return This builder for chaining.
     */
    public Builder setResult(com.duke.protobuf.data.RESULT value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      result_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.duke.protobuf.data.RESULT result = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearResult() {
      
      result_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object errormsg_ = "";
    /**
     * <code>string errormsg = 2;</code>
     * @return The errormsg.
     */
    public java.lang.String getErrormsg() {
      java.lang.Object ref = errormsg_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errormsg_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string errormsg = 2;</code>
     * @return The bytes for errormsg.
     */
    public com.google.protobuf.ByteString
        getErrormsgBytes() {
      java.lang.Object ref = errormsg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errormsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string errormsg = 2;</code>
     * @param value The errormsg to set.
     * @return This builder for chaining.
     */
    public Builder setErrormsg(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      errormsg_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string errormsg = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearErrormsg() {
      
      errormsg_ = getDefaultInstance().getErrormsg();
      onChanged();
      return this;
    }
    /**
     * <code>string errormsg = 2;</code>
     * @param value The bytes for errormsg to set.
     * @return This builder for chaining.
     */
    public Builder setErrormsgBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      errormsg_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.duke.protobuf.data.NCharacterInfo> characters_ =
      java.util.Collections.emptyList();
    private void ensureCharactersIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        characters_ = new java.util.ArrayList<com.duke.protobuf.data.NCharacterInfo>(characters_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.duke.protobuf.data.NCharacterInfo, com.duke.protobuf.data.NCharacterInfo.Builder, com.duke.protobuf.data.NCharacterInfoOrBuilder> charactersBuilder_;

    /**
     * <code>repeated .com.duke.protobuf.data.NCharacterInfo characters = 3;</code>
     */
    public java.util.List<com.duke.protobuf.data.NCharacterInfo> getCharactersList() {
      if (charactersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(characters_);
      } else {
        return charactersBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.duke.protobuf.data.NCharacterInfo characters = 3;</code>
     */
    public int getCharactersCount() {
      if (charactersBuilder_ == null) {
        return characters_.size();
      } else {
        return charactersBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.duke.protobuf.data.NCharacterInfo characters = 3;</code>
     */
    public com.duke.protobuf.data.NCharacterInfo getCharacters(int index) {
      if (charactersBuilder_ == null) {
        return characters_.get(index);
      } else {
        return charactersBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.duke.protobuf.data.NCharacterInfo characters = 3;</code>
     */
    public Builder setCharacters(
        int index, com.duke.protobuf.data.NCharacterInfo value) {
      if (charactersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCharactersIsMutable();
        characters_.set(index, value);
        onChanged();
      } else {
        charactersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.duke.protobuf.data.NCharacterInfo characters = 3;</code>
     */
    public Builder setCharacters(
        int index, com.duke.protobuf.data.NCharacterInfo.Builder builderForValue) {
      if (charactersBuilder_ == null) {
        ensureCharactersIsMutable();
        characters_.set(index, builderForValue.build());
        onChanged();
      } else {
        charactersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.duke.protobuf.data.NCharacterInfo characters = 3;</code>
     */
    public Builder addCharacters(com.duke.protobuf.data.NCharacterInfo value) {
      if (charactersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCharactersIsMutable();
        characters_.add(value);
        onChanged();
      } else {
        charactersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.duke.protobuf.data.NCharacterInfo characters = 3;</code>
     */
    public Builder addCharacters(
        int index, com.duke.protobuf.data.NCharacterInfo value) {
      if (charactersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCharactersIsMutable();
        characters_.add(index, value);
        onChanged();
      } else {
        charactersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.duke.protobuf.data.NCharacterInfo characters = 3;</code>
     */
    public Builder addCharacters(
        com.duke.protobuf.data.NCharacterInfo.Builder builderForValue) {
      if (charactersBuilder_ == null) {
        ensureCharactersIsMutable();
        characters_.add(builderForValue.build());
        onChanged();
      } else {
        charactersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.duke.protobuf.data.NCharacterInfo characters = 3;</code>
     */
    public Builder addCharacters(
        int index, com.duke.protobuf.data.NCharacterInfo.Builder builderForValue) {
      if (charactersBuilder_ == null) {
        ensureCharactersIsMutable();
        characters_.add(index, builderForValue.build());
        onChanged();
      } else {
        charactersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.duke.protobuf.data.NCharacterInfo characters = 3;</code>
     */
    public Builder addAllCharacters(
        java.lang.Iterable<? extends com.duke.protobuf.data.NCharacterInfo> values) {
      if (charactersBuilder_ == null) {
        ensureCharactersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, characters_);
        onChanged();
      } else {
        charactersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.duke.protobuf.data.NCharacterInfo characters = 3;</code>
     */
    public Builder clearCharacters() {
      if (charactersBuilder_ == null) {
        characters_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        charactersBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.duke.protobuf.data.NCharacterInfo characters = 3;</code>
     */
    public Builder removeCharacters(int index) {
      if (charactersBuilder_ == null) {
        ensureCharactersIsMutable();
        characters_.remove(index);
        onChanged();
      } else {
        charactersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.duke.protobuf.data.NCharacterInfo characters = 3;</code>
     */
    public com.duke.protobuf.data.NCharacterInfo.Builder getCharactersBuilder(
        int index) {
      return getCharactersFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.duke.protobuf.data.NCharacterInfo characters = 3;</code>
     */
    public com.duke.protobuf.data.NCharacterInfoOrBuilder getCharactersOrBuilder(
        int index) {
      if (charactersBuilder_ == null) {
        return characters_.get(index);  } else {
        return charactersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.duke.protobuf.data.NCharacterInfo characters = 3;</code>
     */
    public java.util.List<? extends com.duke.protobuf.data.NCharacterInfoOrBuilder> 
         getCharactersOrBuilderList() {
      if (charactersBuilder_ != null) {
        return charactersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(characters_);
      }
    }
    /**
     * <code>repeated .com.duke.protobuf.data.NCharacterInfo characters = 3;</code>
     */
    public com.duke.protobuf.data.NCharacterInfo.Builder addCharactersBuilder() {
      return getCharactersFieldBuilder().addBuilder(
          com.duke.protobuf.data.NCharacterInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .com.duke.protobuf.data.NCharacterInfo characters = 3;</code>
     */
    public com.duke.protobuf.data.NCharacterInfo.Builder addCharactersBuilder(
        int index) {
      return getCharactersFieldBuilder().addBuilder(
          index, com.duke.protobuf.data.NCharacterInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .com.duke.protobuf.data.NCharacterInfo characters = 3;</code>
     */
    public java.util.List<com.duke.protobuf.data.NCharacterInfo.Builder> 
         getCharactersBuilderList() {
      return getCharactersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.duke.protobuf.data.NCharacterInfo, com.duke.protobuf.data.NCharacterInfo.Builder, com.duke.protobuf.data.NCharacterInfoOrBuilder> 
        getCharactersFieldBuilder() {
      if (charactersBuilder_ == null) {
        charactersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.duke.protobuf.data.NCharacterInfo, com.duke.protobuf.data.NCharacterInfo.Builder, com.duke.protobuf.data.NCharacterInfoOrBuilder>(
                characters_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        characters_ = null;
      }
      return charactersBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.duke.protobuf.data.UserCreateCharacterResponse)
  }

  // @@protoc_insertion_point(class_scope:com.duke.protobuf.data.UserCreateCharacterResponse)
  private static final com.duke.protobuf.data.UserCreateCharacterResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.duke.protobuf.data.UserCreateCharacterResponse();
  }

  public static com.duke.protobuf.data.UserCreateCharacterResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UserCreateCharacterResponse>
      PARSER = new com.google.protobuf.AbstractParser<UserCreateCharacterResponse>() {
    @java.lang.Override
    public UserCreateCharacterResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UserCreateCharacterResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UserCreateCharacterResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UserCreateCharacterResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.duke.protobuf.data.UserCreateCharacterResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

