// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/message.proto

package com.duke.protobuf.data;

public interface UserGameEnterRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.duke.protobuf.data.UserGameEnterRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 characterIdx = 1;</code>
   * @return The characterIdx.
   */
  int getCharacterIdx();
}
